<a href="https://colab.research.google.com/github/Eriyon24/Blind-date-Detroit-project/blob/main/Blind_Date_Final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files
import pandas as pd
import numpy as np
import re
from collections import defaultdict
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

### Upload survey file

In [ ]:
uploaded = files.upload()

for filename in uploaded.keys():
  print(f'User uploaded file "{filename}"')
  survey_results = pd.read_csv(filename)
  print(f'DataFrame df1 loaded from {filename}. First 5 rows:')
  display(survey_results.head())

Saving blind_match_detroit_feedback_consistent_20.csv to blind_match_detroit_feedback_consistent_20.csv
User uploaded file "blind_match_detroit_feedback_consistent_20.csv"
DataFrame df1 loaded from blind_match_detroit_feedback_consistent_20.csv. First 5 rows:

,Timestamp,Email Address,Gender,Did you receive any match(es)?,Did you contact any of your match(es),Did you meet any matches in person?,Did you go on a date or plan to meet?,"Overall, how compatible did your match(es)seem?",Did you feel overwhelmed by the number of matches?,"Ideally, how many matches would you prefer next round?",...,"How flexible are you outside your preferred age range?\n\n(Example: If you select 27–31, would you still be open to someone 25 or 33?)",How would you rate your overall experience with the Blind Matchmaking Project?,"If Blind Match Detroit moved to a dedicated website/web app with improved curated matching, communication, participant profiles, and status tracking, what would you be willing to pay per round?",Would you participate again?,Would You want to do Round 2?,What improvements would you like us to make?,Any other suggestions/concerns,Alternate email if needed,What frustrations with modern dating would you like Blind Match Detroit to help solve? (Select all that apply),What features or things would you like to see in the Website/Web app?
0,8/1/2026 18:00,maya.thompson@example.com,Woman,Yes,Yes,Yes,Yes,5 - Excellent,No,1,...,±3 years,5,5-,Yes,Yes,Better compatibility scoring,No additional suggestions.,NaN,Shallow matching; Poor communication,Messaging; Status tracking
1,8/2/2026 18:00,marcus.reed@example.com,Man,Yes,Yes,No,no,4 - Good,No,2,...,±5 years,4,$5,Maybe,Maybe,Better compatibility scoring,No additional suggestions.,NaN,Shallow matching; Poor communication,Profile verification; Interest filters
2,8/3/2026 18:00,arielle.johnson@example.com,Woman,Yes,No,No,No,3 - Average,Yes,1,...,±2 years,3,$5,Maybe,Yes,Fewer but stronger matches,Reduce ghosting somehow.,NaN,Difficulty meeting people organically,Messaging; Status tracking
3,8/4/2026 18:00,devin.carter@example.com,Man,No,NaN,No,No,NaN,No,2,...,±5 years,4,$5,Yes,Yes,More local matches,No additional suggestions.,NaN,Difficulty meeting people organically,Messaging; Status tracking
4,8/5/2026 18:00,nia.brooks@example.com,Woman,Yes,Yes,Yes,Yes,4 - Good,No,2,...,±3 years,5,$5,Yes,Yes,AI-generated match explanations,Reduce ghosting somehow.,NaN,Ghosting; Endless swiping,AI match explanations; Better profiles

### Upload round2 signups

In [ ]:
uploaded = files.upload()

for filename in uploaded.keys():
  print(f'User uploaded file "{filename}"')
  round2_signups = pd.read_csv(filename)
  print(f'DataFrame df2 loaded from {filename}. First 5 rows:')
  display(round2_signups.head())

Saving blind_match_detroit_realistic_signup_20.csv to blind_match_detroit_realistic_signup_20 (1).csv
User uploaded file "blind_match_detroit_realistic_signup_20 (1).csv"
DataFrame df2 loaded from blind_match_detroit_realistic_signup_20 (1).csv. First 5 rows:

,Timestamp,Name,Email,Age,Gender,City/Area,Interested in,Relationship Goal,Preferred Age Range(s),Interests,...,Conversation Starter\nTell your match one fun fact about yourself or ask them a question to break the ice.,Do you have Children?,Do you want children in the future?,Would you date anyone with children?,What religion are you?,Is matching based on religion important to you?,Do you have pets,Is there anything else you'd like your potential match to know before reaching out?,"Ideally, how many matches would you prefer this round?",How far would you be willing to travel to meet a potential match?
0,7/1/2026 9:12,Maya Thompson,maya.thompson@example.com,27,Woman,Detroit,Men,Long-term relationship,27-35,"Trying new restaurants, fitness classes, R&B c...",...,What is the best restaurant you have tried rec...,No,Yes,Maybe,Christian,Yes,No,I am pretty social but I also like calm nights...,2,Up to 30 minutes
1,7/1/2026 9:24,Marcus Reed,marcus.reed@example.com,30,Man,Royal Oak,Women,Serious relationship,25-32,"Basketball, coffee shops, documentaries, cooking",...,What documentary or show have you watched late...,No,Yes,Yes,NaN,Yes,No,I appreciate people who are direct but respect...,2,Meet halfway
2,7/1/2026 10:03,Arielle Johnson,arielle.johnson@example.com,32,Woman,Southfield,Men,Marriage-minded / serious relationship,30-40,"Church, brunch, volunteering, family events, p...",...,What is something you are currently working on...,No,Yes,Maybe,Christian,Yes,No,"Faith is important to me, but I still like to ...",1,Up to 45 minutes
3,7/1/2026 10:18,Devin Carter,devin.carter@example.com,29,Man,Sterling Heights,Women,Open to serious if it feels right,24-31,"MMA, hiking, comedy shows, tacos, personal fin...",...,Would you rather go to a comedy show or try a ...,No,Maybe,Yes,Spiritual,Yes,No,"I joke a lot, but I can be serious when it mat...",2,Up to 30 minutes
4,7/1/2026 11:02,Nia Brooks,nia.brooks@example.com,25,Woman,Dearborn,Men,Dating with intention,25-33,"Art museums, coffee, poetry, thrifting, yoga",...,What is a random thing you are weirdly passion...,No,Unsure,Maybe,Muslim,Yes,Cat,I open up more when the conversation feels nat...,1,Up to 30 minutes

### Upload round 1 matches lookp

In [ ]:
uploaded = files.upload()

for filename in uploaded.keys():
  print(f'User uploaded file "{filename}"')
  round_one_results = pd.read_csv(filename)
  print(f'DataFrame df3 loaded from {filename}. First 5 rows:')
  display(round_one_results.head())

Saving fake_round1_matches_lookup.csv to fake_round1_matches_lookup.csv
User uploaded file "fake_round1_matches_lookup.csv"
DataFrame df3 loaded from fake_round1_matches_lookup.csv. First 5 rows:

,Person,Person Email,Person Bio,Person Social Media,Person Wants Children,Match,Match Email,Match Bio,Match Social Media,Match Wants Children,Score
0,Maya Thompson,maya.thompson@example.com,I work in healthcare and love spending my week...,IG: @maya_demo,Yes,Marcus Reed,marcus.reed@example.com,I am a project manager who enjoys staying acti...,NaN,Yes,90
1,Arielle Johnson,arielle.johnson@example.com,"I am family-oriented, faith-centered, and pass...",IG: @arielle_demo,Yes,Andre Mitchell,andre.mitchell@example.com,I am a business owner and mentor who values fa...,NaN,Yes,88
2,Devin Carter,devin.carter@example.com,I train a few times a week and enjoy being aro...,NaN,Maybe,Nia Brooks,nia.brooks@example.com,"I am creative, observant, and a little quiet a...",IG: @nia_demo,Unsure,87
3,Ethan Williams,ethan.williams@example.com,"I work in tech and enjoy photography, cycling,...",NaN,Yes,Samantha Ellis,samantha.ellis@example.com,I am a marketing professional who enjoys cooki...,IG: @samantha_demo,No,85
4,Lauren Davis,lauren.davis@example.com,"I am outgoing, playful, and usually the friend...",IG: @lauren_demo,Maybe,Malik Brown,malik.brown@example.com,"I am playful, social, and enjoy making people ...",NaN,Unsure,89

Upload

In [ ]:
#Cleaning cities
df["city_clean"] = (
    df["City/Area"]
    .astype(str)
    .str.lower()
    .str.strip()
)

df["city_clean"] = df["city_clean"].replace({
     "st. clair shores": "saint clair shores",
    "st clair shores": "saint clair shores",
    "clinton twp": "clinton township",
    "canton/plymouth": "canton",
    "ann arbor/ypsilanti": "ann arbor",
    "royal oak, mi": "royal oak",
    "detroit, mi": "detroit",
    "brighton/detroit": "brighton"
})

In [ ]:
#Clean column names
df.columns = ([
    "name",
    "email",
    "age",
    "gender",
    "city_area",
    "interested_in",
    "relationship_goal",
    "preferred_age_ranges",
    "interests",
    "ideal_first_date",
    "Short Bio/About You",
    "best_days_available",
    "best_time_availability"
])

print(df.columns.tolist())



#Rename columns
df = df.rename(columns={
    "best_time_availabilty": "best_time_availabilty",
    "preferred_age_range(s)": "preferred_age_range"
})

df.columns

ValueError: Length mismatch: Expected axis has 17 elements, new values have 13 elements

In [ ]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")

print(df.columns.tolist())

['timestamp', 'name', 'email', 'age', 'gender', 'city/area', 'interested_in', 'relationship_goal', 'preferred_age_range(s)', 'interests', 'ideal_first_date', 'short_bio/about_you', 'best_days_available', 'best_time_availabilty', 'i_understand:\n\n•_matches_are_not_guaranteed__\n•_this_is_an_experimental_matchmaking_project__\n•_i_am_responsible_for_my_own_safety_and_interactions__\n•_first_meetings_should_happen_in_public_places__\n•_if_matched,_my_email_may_be_shared_with_my_match_for_communication_purposes__\n\nprivacy_notice\n\nyour_information_will_only_be_used_for_this_matchmaking_project_and_will_not_be_shared_publicly._responses_will_remain_private,_and_only_necessary_information_may_be_shared_with_a_match_for_communication_purposes._if_you_would_like_your_information_removed_at_any_time,_please_let_me_know.', 'email_address', 'city_clean']

In [ ]:
df = df.rename(columns={
    "preferred_age_range(s)": "preferred_age_range",
})

print(df.columns.tolist())

['timestamp', 'name', 'email', 'age', 'gender', 'city/area', 'interested_in', 'relationship_goal', 'preferred_age_range', 'interests', 'ideal_first_date', 'short_bio/about_you', 'best_days_available', 'best_time_availabilty', 'i_understand:\n\n•_matches_are_not_guaranteed__\n•_this_is_an_experimental_matchmaking_project__\n•_i_am_responsible_for_my_own_safety_and_interactions__\n•_first_meetings_should_happen_in_public_places__\n•_if_matched,_my_email_may_be_shared_with_my_match_for_communication_purposes__\n\nprivacy_notice\n\nyour_information_will_only_be_used_for_this_matchmaking_project_and_will_not_be_shared_publicly._responses_will_remain_private,_and_only_necessary_information_may_be_shared_with_a_match_for_communication_purposes._if_you_would_like_your_information_removed_at_any_time,_please_let_me_know.', 'email_address', 'city_clean']

In [ ]:
# Split age range
import re

def get_min_age(age_range_text):
    numbers = re.findall(r"\d+", str(age_range_text))
    numbers = [int(num) for num in numbers]
    return min(numbers)

def get_max_age(age_range_text):
    numbers = re.findall(r"\d+", str(age_range_text))
    numbers = [int(num) for num in numbers]
    return max(numbers)

df["min_age"] = df["preferred_age_range"].apply(get_min_age)
df["max_age"] = df["preferred_age_range"].apply(get_max_age)

df[["name", "preferred_age_range", "min_age", "max_age"]].head()

                name       preferred_age_range  min_age  max_age
0              Corey       22–26, 27–31, 32–36       22       36
1     Taylor Carlini              27–31, 32–36       27       36
2              Suhas  22–26, 27–31, 32–36, 36+       22       36
3              Will               22–26, 27–31       22       31
4  zachary Goldstein       22–26, 27–31, 32–36       22       36

In [ ]:
# Combine interests + bio

df["combined_text"] = (
    df["interests"].fillna("") + " " +
    df["short_bio/about_you"].fillna("") + " " +
    df["ideal_first_date"].fillna("")
)

df[["name", "combined_text"]].head()

                name                                      combined_text
0              Corey  Movies, Travel, Food, Sports, Gaming, Music, C...
1     Taylor Carlini  Gym, Travel, Food, Hiking, Music Emergency vet...
2              Suhas  Gym, Movies, Travel, Food, Hiking, Music, Nigh...
3              Will   Gym, Movies, Travel, Food, Sports, Hiking, Mus...
4  zachary Goldstein  Gym, Travel, Sports, Hiking, car/motorsports  ...

In [ ]:
#NLP turn text into similarity scores

vectorizer = TfidfVectorizer(
    stop_words="english"
)

matrix = vectorizer.fit_transform(
    df["combined_text"]
)

similarity = cosine_similarity(matrix)

print(similarity)

[[1.         0.12232712 0.05554116 ... 0.09133748 0.03675599 0.01633623]
 [0.12232712 1.         0.02908865 ... 0.06652202 0.01673036 0.03112034]
 [0.05554116 0.02908865 1.         ... 0.04186622 0.10740129 0.08663762]
 ...
 [0.09133748 0.06652202 0.04186622 ... 1.         0.09198681 0.10268672]
 [0.03675599 0.01673036 0.10740129 ... 0.09198681 1.         0.08154704]
 [0.01633623 0.03112034 0.08663762 ... 0.10268672 0.08154704 1.        ]]

In [ ]:
def older_participant_bonus(person1, person2):

    #Both people are 50+
    if person1["age"] >= 50 and person2["age"] >= 50:
        return 200

    #Both people are 40+
    if person1["age"] >= 40 and person2["age"] >= 40:
        return 150

    #Both people are 36+
    if person1["age"] >= 36 and person2["age"] >= 36:
        return 100

    return 0

In [ ]:
def get_county(city):

    oakland = [
        "royal oak", "ferndale", "troy", "southfield",
        "novi", "farmington hills", "holly", "waterford",
        "auburn hills", "clarkston", "franklin","rochester hills","birmingham","west bloomfield","northville"
    ]

    wayne = [
        "detroit", "dearborn", "livonia", "westland",
        "canton", "plymouth","grosse pointe"
    ]

    macomb = [
        "sterling heights", "clinton township",
        "roseville", "saint clair shores", "macomb township"
    ]

    washtenaw = [
        "ann arbor", "ypsilanti","brighton","south lyon"
    ]

    if city in oakland:
        return "oakland"

    if city in wayne:
        return "wayne"

    if city in macomb:
        return "macomb"

    if city in washtenaw:
        return "washtenaw"

    return "unknown"

In [ ]:
# West / far city lock rule

west_lock_cities = [
    "ann arbor",
    "ypsilanti",
    "brighton",
    "south lyon",
    "northville",
    "canton",
    "plymouth",
    "west bloomfield",
    "farmington hills"
]

def west_city_lock(person1, person2):

    city1 = person["city_clean"]
    city1 = person2["city_clean"]

    if city1 in west_lock_cities and city2 not in west_lock_cities:
        return False

    if city2 in west_lock_cities and city1 not in west_lock_cities:
        return false

    return True

In [ ]:
def calculate_match_score(person1, person2, i, j):

    score = 0

    # your gender checks here

    # your age checks here

    # west city lock
    if not west_city_lock(person1, person2):
        return 0

    # rest of your scoring below

In [ ]:
#Create county column

df["county_clean"] = df["city_clean"].apply(get_county)

In [ ]:
#location bonus function
def location_bonus(person1, person2):

    county1 = person1["county_clean"]
    county2 = person2["county_clean"]

    # same county
    if county1 == county2:
        return 15

    nearby_pairs = [
        ("oakland", "wayne"),
        ("oakland", "macomb"),
        ("wayne", "macomb"),
        ("wayne", "washtenaw"),
        ("oakland", "washtenaw")
    ]

    pair = tuple(sorted([county1, county2]))

    nearby_pairs_clean = [
        tuple(sorted(p)) for p in nearby_pairs
    ]

    # nearby county
    if pair in nearby_pairs_clean:
        return 8

    return 0

In [ ]:
#Bio key words for matching
bio_keywords = {
    "fitness": ["gym", "fitness", "working out", "active", "training"],
    "food": ["food", "restaurants", "coffee", "brunch", "dinner"],
    "travel": ["travel", "adventure", "explore"],
    "family": ["family", "kids", "children"],
    "faith": ["christian", "faith", "church", "god"],
    "outdoors": ["hiking", "nature", "outdoors", "walks"],
    "creative": ["art", "music", "creative", "writing"],
    "career": ["career", "ambitious", "driven", "business"]
}

In [ ]:
#Function to find bio traits
def get_bio_traits(bio):

    bio = str(bio).lower()
    traits = []

    for trait, words in bio_keywords.items():
        for word in words:
            if word in bio:
                traits.append(trait)
                break

    return set(traits)

In [ ]:
#Bio boosting for matching
def bio_bonus(person1, person2):

    traits1 = get_bio_traits(person1["short_bio/about_you"])
    traits2 = get_bio_traits(person2["short_bio/about_you"])

    shared_traits = traits1.intersection(traits2)

    return len(shared_traits) * 10

In [ ]:
# Matching Function
def calculate_match_score(person1, person2, i, j):

    score = 0

    score += location_bonus(person1, person2)

    score += older_participant_bonus(person1,person2)

    score += bio_bonus(person1, person2)


    #36+ bonus

    score += age_36_plus_bonus(
        person1,
        person2
    )

    #Gender
    if person1["gender"] != person2["interested_in"]:
        return 0

    if person2["gender"] != person1["interested_in"]:
        return 0


    #Older participants 36+

    age_difference = abs(
        person1["age"] - person2["age"]
    )




    if person1["age"] >= 36 or person2["age"] >= 36:

        if age_difference > 15:
            return 0

    #Normal matching for younger particpants

    #Age
    if not(
        person1["min_age"]
        <= person2["age"]
        <= person1["max_age"]
    ):
        return 0

    if not (
        person2["min_age"]
        <= person1["age"]
        <= person2["max_age"]
    ):
        return 0

    # Relationship Goal
    if (
        person1["relationship_goal"]
        ==
        person2["relationship_goal"]
    ):
        score += 20


    elif (
        person1["relationship_goal"] == "Open to Either"
        or
        person2["relationship_goal"] == "Open to Either"
    ):

        score += 15


           # Shared Interests
    interests1 = set(
        str(person1["interests"]).lower().split(",")
    )

    interests2 = set(
        str(person2["interests"]).lower().split(",")
    )

    shared_interests = interests1.intersection(interests2)

    score += len(shared_interests) * 10


    # Ideal First Date Match
    if (
        person1["ideal_first_date"]

        ==
        person2["ideal_first_date"]
    ):

        score += 20

    # NLP BIO SCORE
    score += similarity[i][j] * 50

    return score

In [ ]:
#Replace gender labels to match
df["gender"] = df["gender"].replace({
    "Male" : "Men",
    "Female": "Women"
})

print(df["gender"].unique())
print(df["interested_in"].unique())

['Men' 'Women']
['Women' 'Men' 'Men, Women']

In [ ]:
print(df["gender"].unique())
print(df["interested_in"].unique())
print(df["relationship_goal"].unique())

['Men' 'Women']
['Women' 'Men' 'Men, Women']
['Open to Either' 'Serious Relationship' 'Casual']

In [ ]:
#fix age columns
df["age"] = pd.to_numeric(df["age"], errors="coerce")
df["min_age"] = pd.to_numeric(df["min_age"], errors="coerce")
df["max_age"] = pd.to_numeric(df["max_age"], errors="coerce")

print(df[["age", "min_age", "max_age"]].dtypes)

age        float64
min_age      int64
max_age      int64
dtype: object

In [ ]:
def age_36_plus_bonus(person1, person2):

    if person1["age"] >= 36 and person2["age"] >= 36:
        return 100

    return 0

In [ ]:
# Find Matches

matches = []

MAX_MATCHES = 4

match_counts = {}

max_times_matched = 2

for i in range(len(df)):

    person1 = df.iloc[i]
    person1_name = person1["name"]

    best_match = None

    best_score = 0

    for j in range(len(df)):

        #Skip same person
        if i == j:
            continue

        person2 = df.iloc[j]

        person2_name = person2["name"]

        #skip this person if they already have too many matches
        if match_counts.get(person2_name, 0) >= max_times_matched:
            continue


        # Calculate score
        score = calculate_match_score(
            person1,
            person2,
            i,
            j
        )

        # Save best match
        if score > best_score:

            best_score = score

            best_match = person2["name"]

        #Find best match email:
        if best_match is not None:

            best_match_email = df[
                df["name"] == best_match
            ]["email"].values[0]

        else:

            best_match_email = None





        # skip if already at limit
        if match_counts.get(person1["name"], 0) >= MAX_MATCHES:
            continue

        if match_counts.get(person2["name"], 0) >= MAX_MATCHES:
            continue


           # Save result
    matches.append({

        "Person": person1["name"],

        "Best Match": best_match,

        "Compatibility Score": best_score,

        "Person Email": person1["email"],

        "Best Match Email": best_match_email
    })


        # increase match counts
    match_counts[person1["name"]] = (
        match_counts.get(person1["name"], 0) + 1
    )

    match_counts[person2["name"]] = (
        match_counts.get(person2["name"], 0) + 1
    )

        # count how many time someone got matched
    if best_match is not None and best_score > 0:
        match_counts[person1_name] = match_counts.get(person1_name, 0) + 1
        match_counts[best_match] = match_counts.get(best_match, 0) + 1



results_df = pd.DataFrame(matches)

results_df

,Person,Best Match,Compatibility Score,Person Email,Best Match Email
0,Corey,Pritika Sally,78.148648,coreyross1996@gmail.com,tomlinsonhes@gmail.com
1,Taylor Carlini,Jeromy,98.518841,taylorcarlini@gmail.com,jerooomyidk@gmail.com
2,Suhas,Regan,102.528066,suhas1597@gmail.com,reganhavens@gmail.com
3,Will,KayDee,111.081433,williamrittenhouse8@gmail.com,kd.muhleck@gmail.com
4,zachary Goldstein,Mady Berns,79.742865,zageagle@gmail.com,Bernsmadalyn@gmail.com
...,...,...,...,...,...
134,Puneet,None,0.000000,testsubject273@gmail.com,None
135,Terri,None,0.000000,terriswing@yahoo.com,None
136,Samantha Jacobs,None,0.000000,samantha.jacobs920@gmail.com,None
137,Kate,None,0.000000,kwcady@gmail.com,None
138,Ashwin,None,0.000000,acupadhyay@oakland.edu,None

In [ ]:
#no match results
no_match_df = results_df[
(results_df["Best Match"].isna()) |
(results_df["Compatibility Score"] == 0)
 ]

no_match_df

,Person,Best Match,Compatibility Score,Person Email,Best Match Email
5,Erica Traskos,None,0.0,etraskos11@gmail.com,None
14,Mara Matta,None,0.0,matta.maria.jalil@gmail.com,None
19,Crystal Stewart,None,0.0,crystalnicstewart@gmail.com,None
28,Sam Sovran,None,0.0,sam.sovran@gmail.com,None
29,Karen Smith,None,0.0,k.e.smith.1986@gmail.com,None
37,Shayna,None,0.0,waldman.shayna@gmail.com,None
38,Vigul Desai,None,0.0,viguldesai76@gmail.com,None
46,Danny Ashcraft,None,0.0,dashcraftjr@gmail.com,None
57,Alejandro Perkins,None,0.0,aloaperkins@gmail.com,None
59,Sola Mewha,None,0.0,solamewha97@gmail.com,None
66,Loren Shevitz,None,0.0,8x2dmvyfv9@privaterelay.appleid.com,None
67,Sara Walkup,None,0.0,sara.walkup@gmail.com,None
68,Samantha S,None,0.0,sjstover7@gmail.com,None
74,Natalie,None,0.0,ntalife@gmail.com,None
78,Ethan Dietrich,None,0.0,ethantd123@gmail.com,None
79,Abhi,None,0.0,abhijeet.antin@gmail.com,None
82,Maria,None,0.0,menea13@gmail.com,None
87,Nihal,None,0.0,nihalnavale@outlook.com,None
91,Tyler,None,0.0,tbrown12@svsu.edu,None
92,Eric Giles,None,0.0,ericgs@umich.edu,None
93,Eyvaughn Standifer,None,0.0,standifereyvaughn@gmail.com,None
94,Ryjean Reid,None,0.0,900602019.reid@gmail.com,None
98,Jonathan Paulino,None,0.0,jdpaulino2016@gmail.com,None
99,Harjas Dadiyal,None,0.0,singh.harjas8@gmail.com,None
101,Jeromy,None,0.0,jerooomyidk@gmail.com,None
102,Leila,None,0.0,leila.anani@gmail.com,None
104,Sarah Dooley,None,0.0,sedooley@comcast.net,None
105,Kyle Russ,None,0.0,kyleruss27@gmail.com,None
106,Lauren,None,0.0,lflorkey@comcast.net,None
107,Brian,None,0.0,bsbrogs05@yahoo.com,None
110,Lindsay Rogers,None,0.0,lindsayfrogers@gmail.com,None
111,Leonel Cuba,None,0.0,leonel.cuba213@gmail.com,None
112,Niki,None,0.0,nikiboivin09@yahoo.com,None
113,Evan,None,0.0,evan.c.kennedy@gmail.com,None
114,Michelle,None,0.0,michelleserra73@icloud.com,None
115,Lissa,None,0.0,elissalund@gmail.com,None
116,Lucia Sosa,None,0.0,luciamagalysosa@gmail.com,None
117,Julien Medel,None,0.0,asdmedel@gmail.com,None
119,Evan D'Silva,None,0.0,edsilva@umich.edu,None
120,Katy,None,0.0,kmcgarry22@adrian.edu,None
121,Isha Oberoi,None,0.0,isha.ross187@gmail.com,None
122,Edona,None,0.0,edona.haziri88@hotmail.com,None
123,Michael Goodwin,None,0.0,migoodwin.49@gmail.com,None
124,Andrew Quang,None,0.0,quangwenhao@gmail.com,None
126,Nick Hughes,None,0.0,nicholas.a.hughes17@gmail.com,None
127,Nikohl,None,0.0,nikohlsands@gmail.comh,None
128,Alex,None,0.0,alexander.rea5@yahoo.com,None
129,Quinton Lemanski,None,0.0,quinton.lemanski@gmail.com,None
130,Dave,None,0.0,Spedmonds47@gmail.com,None
131,Andrew Fabry,None,0.0,afabry@comcast.net,None
132,MELANIE BETEL,None,0.0,betelmel@umich.edu,None
133,Alissa,None,0.0,alissa.curtis518@gmail.com,None
134,Puneet,None,0.0,testsubject273@gmail.com,None
135,Terri,None,0.0,terriswing@yahoo.com,None
136,Samantha Jacobs,None,0.0,samantha.jacobs920@gmail.com,None
137,Kate,None,0.0,kwcady@gmail.com,None
138,Ashwin,None,0.0,acupadhyay@oakland.edu,None

In [ ]:
#second pass matches
second_pass_matches = []

for i in range(len(no_match_df)):

    person_name = no_match_df.iloc[i]["Person"]

    person1 = df[df["name"] == person_name].iloc[0]

    person1_index = df[df["name"] == person_name].index[0]

    best_score = 0
    best_match = None

    for j in range(len(df)):

        person2 = df.iloc[j]

        if person1["name"] == person2["name"]:
            continue

        score = calculate_match_score(
            person1,
            person2,
            person1_index,
            j
        )

        if score > best_score:
            best_score = score
            best_match = person2["name"]

    second_pass_matches.append({
        "Person": person1["name"],
        "Second Pass Match": best_match,
        "Compatibility Score": best_score
    })

second_pass_df = pd.DataFrame(second_pass_matches)

second_pass_df

                Person Second Pass Match  Compatibility Score
0        Erica Traskos              None             0.000000
1           Mara Matta              None             0.000000
2      Crystal Stewart              None             0.000000
3           Sam Sovran              None             0.000000
4          Karen Smith              None             0.000000
5               Shayna              None             0.000000
6          Vigul Desai              None             0.000000
7       Danny Ashcraft              Mark            77.822635
8   Alejandro Perkins             KayDee            97.266212
9           Sola Mewha              None             0.000000
10       Loren Shevitz              None             0.000000
11         Sara Walkup              None             0.000000
12          Samantha S              None             0.000000
13             Natalie              None             0.000000
14      Ethan Dietrich            KayDee            73.147441
15                Abhi  Angela Rodriguez            71.509195
16               Maria              None             0.000000
17               Nihal  Angela Rodriguez           109.012533
18              Tyler             KayDee           102.798489
19          Eric Giles       Kiara Greer            72.709070
20  Eyvaughn Standifer              None             0.000000
21         Ryjean Reid       Lily Nguyen            43.091892
22    Jonathan Paulino             Regan            86.432247
23      Harjas Dadiyal  Angela Rodriguez           103.786365
24              Jeromy            KayDee           119.858416
25               Leila               Sai           121.909806
26        Sarah Dooley              None             0.000000
27          Kyle Russ     Rhiannon Shook            58.696549
28              Lauren              None             0.000000
29               Brian              None             0.000000
30      Lindsay Rogers              None             0.000000
31         Leonel Cuba  Olivia Patercsak           103.197056
32               Niki               None             0.000000
33                Evan    Rhiannon Shook            97.169648
34           Michelle               None             0.000000
35              Lissa               None             0.000000
36         Lucia Sosa                Rob            89.847085
37       Julien Medel        Kiara Greer           104.490183
38        Evan D'Silva  reigan Henderson            78.420043
39                Katy              None             0.000000
40        Isha Oberoi               None             0.000000
41              Edona               None             0.000000
42     Michael Goodwin    Taylor Carlini            72.148670
43        Andrew Quang  reigan Henderson            72.533981
44         Nick Hughes             Regan            93.946132
45              Nikohl              None             0.000000
46                Alex              Kim            103.420442
47   Quinton Lemanski             KayDee            80.116595
48                Dave             Regan           107.258357
49        Andrew Fabry            KayDee            99.710702
50       MELANIE BETEL  Vincenzo Francis            60.125848
51              Alissa              None             0.000000
52              Puneet    Rhiannon Shook           129.523275
53               Terri              None             0.000000
54     Samantha Jacobs              None             0.000000
55                Kate              None             0.000000
56              Ashwin            KayDee           104.156427

In [ ]:
# Get names of people who did not match
no_match_names = no_match_df["Person"].tolist()

#Go back to orginal df and find unmatched people age 36+
older_no_match_df = df[
    (df["name"].isin(no_match_names)) &
    (df["age"] >= 36)
]

older_no_match_df

,timestamp,name,email,age,gender,city/area,interested_in,relationship_goal,preferred_age_range,interests,...,short_bio/about_you,best_days_available,best_time_availabilty,"i_understand:\n\n•_matches_are_not_guaranteed__\n•_this_is_an_experimental_matchmaking_project__\n•_i_am_responsible_for_my_own_safety_and_interactions__\n•_first_meetings_should_happen_in_public_places__\n•_if_matched,_my_email_may_be_shared_with_my_match_for_communication_purposes__\n\nprivacy_notice\n\nyour_information_will_only_be_used_for_this_matchmaking_project_and_will_not_be_shared_publicly._responses_will_remain_private,_and_only_necessary_information_may_be_shared_with_a_match_for_communication_purposes._if_you_would_like_your_information_removed_at_any_time,_please_let_me_know.",email_address,city_clean,min_age,max_age,combined_text,county_clean
28,5/14/2026 17:20:26,Sam Sovran,sam.sovran@gmail.com,37.0,Men,Royal Oak,Women,Open to Either,32–36,"Gym, Movies, Travel, Sports, Reading, Gaming, ...",...,Single guy completely sick of the online datin...,"Wednesday, Friday, Saturday",Evening,Yes,sam.sovran@gmail.com,royal oak,32,36,"Gym, Movies, Travel, Sports, Reading, Gaming, ...",oakland
29,5/14/2026 17:56:37,Karen Smith,k.e.smith.1986@gmail.com,39.0,Women,"Ferndale, MI",Men,Open to Either,36+,"Travel, Food, Sports, Reading, Hiking, Music",...,\n\nMoved to Michigan from Georgia in January ...,"Friday, Saturday, Sunday","Afternoon, Evening",Yes,k.e.smith.1986@gmail.com,"ferndale, mi",36,36,"Travel, Food, Sports, Reading, Hiking, Music \...",unknown
37,5/15/2026 3:54:02,Shayna,waldman.shayna@gmail.com,38.0,Women,"Ferndale, MI",Men,Open to Either,"32–36, 36+","Gym, Movies, Travel, Food, Sports, Reading, Hi...",...,Former elementary teacher turned functional mu...,"Tuesday, Wednesday, Thursday, Friday, Saturday...","Afternoon, Evening, Late Night",Yes,waldmanshayna@gmail.com,"ferndale, mi",32,36,"Gym, Movies, Travel, Food, Sports, Reading, Hi...",unknown
38,5/15/2026 13:07:02,Vigul Desai,viguldesai76@gmail.com,49.0,Women,Clarkston,Men,Open to Either,40+,"Movies, Travel, Food, Reading, Music, Nightlif...",...,"Independent, spontaneous, kind, compassionate ...","Thursday, Friday, Saturday, Sunday",Evening,Yes,viguldesai76@gmail.com,clarkston,40,40,"Movies, Travel, Food, Reading, Music, Nightlif...",oakland
66,5/19/2026 11:17:57,Loren Shevitz,8x2dmvyfv9@privaterelay.appleid.com,53.0,Men,West Bloomfield,Women,Open to Either,"32–36, 36+","Movies, Travel, Food, Sports, Hiking, Music",...,NaN,"Tuesday, Friday, Saturday, Sunday",Evening,Yes,8x2dmvyfv9@privaterelay.appleid.com,west bloomfield,32,36,"Movies, Travel, Food, Sports, Hiking, Music K...",oakland
67,5/19/2026 11:50:12,Sara Walkup,sara.walkup@gmail.com,43.0,Women,Detroit,Men,Open to Either,36+,"Gym, Travel, Food, Sports, Hiking, Music, Nigh...",...,Just moved back to Michigan after 20 years in ...,"Monday, Tuesday, Wednesday, Thursday, Friday","Afternoon, Evening",Yes,sara.walkup@gmail.com,detroit,36,36,"Gym, Travel, Food, Sports, Hiking, Music, Nigh...",wayne
68,5/19/2026 12:03:05,Samantha S,sjstover7@gmail.com,38.0,Women,NaN,Men,Serious Relationship,"32–36, 36+","Gym, Movies, Travel, Hiking, Music",...,I’m a charismatic energetic woman who loves tr...,"Monday, Tuesday, Friday","Afternoon, Evening",Yes,sjstover7@gmail.com,nan,32,36,"Gym, Movies, Travel, Hiking, Music I’m a chari...",unknown
74,5/19/2026 19:49:33,Natalie,ntalife@gmail.com,42.0,Women,Ann Arbor/Ypsilanti but open,Men,Serious Relationship,"32–36, 36+","Movies, Travel, Food, Reading, Music, Professi...",...,"A sweet, down-to-Earth, Christian girl attract...","Thursday, Friday, Saturday, Sunday","Afternoon, Evening",Yes,ntalife@gmail.com,ann arbor/ypsilanti but open,32,36,"Movies, Travel, Food, Reading, Music, Professi...",unknown
82,5/20/2026 13:58:44,Maria,menea13@gmail.com,46.0,Women,Royal Oak,Men,Serious Relationship,36+,"Gym, Movies, Travel, Food, Reading, Hiking, Music",...,"Energetic, outgoing, and active. Looking for s...","Monday, Tuesday, Thursday, Sunday","Afternoon, Evening",Yes,menea13@gmail.com,royal oak,36,36,"Gym, Movies, Travel, Food, Reading, Hiking, Mu...",oakland
93,5/21/2026 10:07:09,Eyvaughn Standifer,standifereyvaughn@gmail.com,37.0,Women,Royal oak,Men,Open to Either,"32–36, 36+","Gym, Movies, Travel, Food, Reading, Gaming, Mu...",...,"I'm 37, mother of 2, cosmetologist, photograph...","Thursday, Friday, Saturday","Afternoon, Evening, Late Night",Yes,standifereyvaughn@gmail.com,royal oak,32,36,"Gym, Movies, Travel, Food, Reading, Gaming, Mu...",oakland
94,5/21/2026 10:12:39,Ryjean Reid,900602019.reid@gmail.com,37.0,Men,Detroit,Women,Serious Relationship,"22–26, 27–31, 32–36, 36+","Gym, Movies, Travel, Cannabis",...,37 year old transplant from Georgia. Always on...,"Monday, Tuesday, Wednesday, Thursday, Friday","Evening, Late Night",Yes,900602019.reid@gmail.com,detroit,22,36,"Gym, Movies, Travel, Cannabis 37 year old tran...",wayne
106,5/21/2026 13:44:49,Lauren,lflorkey@comcast.net,38.0,Women,Trenton (but I spend a lot of time/plan to mov...,Men,Open to Either,36+,"Gym, Travel, Food, Sports, Reading",...,Have a 6yo son. Have an MBA and balance an int...,"Friday, Saturday, Sunday","Afternoon, Evening",Yes,lflorkey@comcast.net,trenton (but i spend a lot of time/plan to mov...,36,36,"Gym, Travel, Food, Sports, Reading Have a 6yo ...",unknown
107,5/21/2026 13:54:28,Brian,bsbrogs05@yahoo.com,38.0,Men,Royal Oak,Women,Open to Either,"32–36, 36+","Gym, Movies, Travel, Food, Sports, Gaming",...,"38, male with a B.A. in economics, based in Ro...","Thursday, Friday, Saturday, Sunday","Afternoon, Evening",Yes,bsbrogs05@yahoo.com,royal oak,32,36,"Gym, Movies, Travel, Food, Sports, Gaming 38, ...",oakland
112,5/21/2026 14:44:27,Niki,nikiboivin09@yahoo.com,55.0,Women,Royal Oak,Men,Open to Either,36+,"Gym, Movies, Travel, Food, Sports, Reading, Hi...",...,I am a 55 year old nurse practitioner with one...,"Thursday, Saturday, Sunday",Evening,Yes,nikiboivin09@yahoo.com,royal oak,36,36,"Gym, Movies, Travel, Food, Sports, Reading, Hi...",oakland
114,5/21/2026 15:05:01,Michelle,michelleserra73@icloud.com,52.0,Women,Royal Oak,Men,Open to Either,45+,"Movies, Travel, Food, Reading, Music",...,Divorced mom of two amazing college-aged kids....,"Thursday, Friday, Saturday, Sunday",Evening,Yes,michelleserra73@icloud.com,royal oak,45,45,"Movies, Travel, Food, Reading, Music Divorced ...",oakland
115,5/21/2026 16:05:44,Lissa,elissalund@gmail.com,54.0,Women,Royal Oak,Women,Open to Either,36+,"Movies, Travel, Food, Sports, Music",...,"Professional, established woman looking for co...","Wednesday, Thursday, Friday, Saturday, Sunday","Evening, Late Night",Yes,elissalund@gmail.com,royal oak,36,36,"Movies, Travel, Food, Sports, Music Profession...",oakland
127,5/21/2026 23:18:56,Nikohl,nikohlsands@gmail.comh,38.0,Women,Southfield/Berkley,Men,Open to Either,36+,"Travel, Food, Reading, Hiking, Music",...,"Ambitious girlie with a witchy heart, a travel...","Saturday, Sunday","Afternoon, Evening",Yes,nikohlsands@gmail.comh,southfield/berkley,36,36,"Travel, Food, Reading, Hiking, Music Ambitious...",unknown
128,5/21/2026 23:29:22,Alex,alexander.rea5@yahoo.com,36.0,Men,Royal Oak,Women,Open to Either,"27–31, 32–36, 36+","Movies, Travel, Food, Sports, Reading, Hiking,...",...,36-year-old dad of two with a career in tech a...,"Tuesday, Wednesday, Friday, Saturday, Sunday","Evening, Late Night",Yes,alexander.rea5@yahoo.com,royal oak,27,36,"Movies, Travel, Food, Sports, Reading, Hiking,...",oakland
133,5/22/2026 10:51:33,Alissa,alissa.curtis518@gmail.com,37.0,Women,Roseville,Men,Serious Relationship,"32–36, 36+","Gym, Movies, Sports, Reading, Outdoor activiti...",...,"I’m 37, been single 6 years, live alone with m...","Saturday, Sunday","Afternoon, Evening",Yes,alissa.curtis518@gmail.com,roseville,32,36,"Gym, Movies, Sports, Reading, Outdoor activiti...",macomb
135,5/22/2026 14:08:30,Terri,terriswing@yahoo.com,51.0,Women,Warren,Men,Open to Either,45-55,"Gym, Movies, Travel, Food, Hiking, Music, Nigh...",...,"Widowed, 51 Warren. I’m a hairstylist, volunte...","Monday, Tuesday, Wednesday, Thursday, Friday, ...","Afternoon, Evening, Late Night",Yes,terriswing@yahoo.com,warren,45,55,"Gym, Movies, Travel, Food, Hiking, Music, Nigh...",unknown
137,5/22/2026 20:04:34,Kate,kwcady@gmail.com,59.0,Women,Royal Oak,Men,Open to Either,55-65,"Gym, Movies, Travel, Food, Sports, Reading, Hi...",...,"30+ years in publishing and love my job, get t...","Friday, Saturday, Sunday","Morning, Evening",Yes,kwcady@gmail.com,royal oak,55,65,"Gym, Movies, Travel, Food, Sports, Reading, Hi...",oakland

In [ ]:
print(older_no_match_df[["name", "age", "gender", "interested_in"]])
print(len(older_no_match_df))

                   name   age gender interested_in
28           Sam Sovran  37.0    Men         Women
29          Karen Smith  39.0  Women           Men
37               Shayna  38.0  Women           Men
38          Vigul Desai  49.0  Women           Men
66        Loren Shevitz  53.0    Men         Women
67          Sara Walkup  43.0  Women           Men
68           Samantha S  38.0  Women           Men
74              Natalie  42.0  Women           Men
82                Maria  46.0  Women           Men
93   Eyvaughn Standifer  37.0  Women           Men
94          Ryjean Reid  37.0    Men         Women
106              Lauren  38.0  Women           Men
107               Brian  38.0    Men         Women
112               Niki   55.0  Women           Men
114           Michelle   52.0  Women           Men
115              Lissa   54.0  Women         Women
127              Nikohl  38.0  Women           Men
128                Alex  36.0    Men         Women
133              Alissa  37.0  Women           Men
135               Terri  51.0  Women           Men
137                Kate  59.0  Women           Men
21

In [ ]:
# Redo calculate older matches
def calculate_older_match_score(person1, person2):

    score = 0

    # skip same person
    if person1["name"] == person2["name"]:
        return 0

    # both must be 36+
    if person1["age"] < 36 or person2["age"] < 36:
        return 0

    # gender preference check
    if person1["interested_in"] != person2["gender"]:
        return 0

    if person2["interested_in"] != person1["gender"]:
        return 0

    score += 100

    return score

In [ ]:
#Test
person1 = older_no_match_df.iloc[0]
person2 = older_no_match_df.iloc[1]

print(calculate_older_match_score(person1, person2))

100

In [ ]:
# match older people with all older people
older_pool = df[df["age"] >= 36]

older_matches = []

for i in range(len(older_no_match_df)):

    person1 = older_no_match_df.iloc[i]

    best_score = 0
    best_match = None

    for j in range(len(older_pool)):

        person2 = older_pool.iloc[j]

        if person1["name"] == person2["name"]:
            continue

        score = calculate_older_match_score(person1, person2)

        if score > best_score:
            best_score = score
            best_match = person2["name"]

    older_matches.append({
        "Person": person1["name"],
        "Older Match": best_match,
        "Compatibility Score": best_score

    })

older_matches_df = pd.DataFrame(older_matches)

#Limit matches per person
older_matches_df["match_rank"] = (
    older_matches_df.groupby("Older Match")
    .cumcount() + 1
)

older_matches_df = older_matches_df[
    older_matches_df["match_rank"] <= 3
]

older_matches_df = older_matches_df.drop(
    columns=["match_rank"]
)

older_matches_df.head(10)

           Person       Older Match  Compatibility Score
0      Sam Sovran       Karen Smith                  100
1     Karen Smith  Vincenzo Francis                  100
2          Shayna  Vincenzo Francis                  100
3     Vigul Desai  Vincenzo Francis                  100
4   Loren Shevitz       Karen Smith                  100
10    Ryjean Reid       Karen Smith                  100

In [ ]:
# Force Eriyon to get a match

my_name = "Eriyon Adams"

my_index = df[df["name"] == my_name].index[0]
me = df.loc[my_index]

my_matches = []

for j in range(len(df)):

    other_person = df.iloc[j]

    if other_person["name"] == my_name:
        continue

    score = calculate_match_score(
        me,
        other_person,
        my_index,
        j
    )

    if score > 0:


      my_matches.append({
            "Person": my_name,
            "Match": other_person["name"],
            "Match Email": other_person["email"],
            "Score": score
        })

my_matches_df = pd.DataFrame(my_matches)

my_matches_df = my_matches_df.sort_values(
    by="Score",
    ascending=False
)

my_top_matches = my_matches_df.head(4)

my_top_matches

         Person             Match                  Match Email       Score
7  Eriyon Adams    Rhiannon Shook   rhiannonelaine17@gmail.com  108.943008
0  Eriyon Adams       Kiara Greer        greer.kiara@yahoo.com  101.919968
8  Eriyon Adams            KayDee         kd.muhleck@gmail.com   95.376948
6  Eriyon Adams  Angela Rodriguez  angierodriguez017@gmail.com   92.312685

In [ ]:
#email

import smtplib

from email.message import EmailMessage

sender_email = "blindmatchdetroit@gmail.com"

app_password = "ylad sdrj tsuz zdim"

In [ ]:
def first_name(name):
    return str(name).strip().split()[0]

In [ ]:
# Clean column names for main table
main_matches_clean = results_df.rename(columns={
    "Best Match": "Match",
    "Best Match Email": "Match Email",
    "Compatibility Score": "Score"
})[
    ["Person", "Person Email", "Match", "Match Email", "Score",]
]

# Lookup table from orginal df
info_lookup = df.drop_duplicates(subset="name").set_index("name")


# Add email columns
main_matches_clean["Person Email"] = main_matches_clean["Person"].map(
    info_lookup["email"]
)


main_matches_clean["Match Email"] = main_matches_clean["Match"].map(
    info_lookup["email"]
)

# Add match details from original df
main_matches_clean["ideal_first_date"] = main_matches_clean["Match"].map(
    info_lookup["ideal_first_date"]
)

main_matches_clean["short_bio/about_you"] = main_matches_clean["Match"].map(
    info_lookup["short_bio/about_you"]
)

main_matches_clean["best_days_available"] = main_matches_clean["Match"].map(
    info_lookup["best_days_available"]
)

main_matches_clean["best_time_availabilty"] = main_matches_clean["Match"].map(
    info_lookup["best_time_availabilty"]
)



# NOW select final columns
main_matches_clean = main_matches_clean[
    [
        "Person",
        "Person Email",
        "Match",
        "Match Email",
        "Score",
        "ideal_first_date",
        "short_bio/about_you",
        "best_days_available",
        "best_time_availabilty"
    ]
]

main_matches_clean.head()

,Person,Person Email,Match,Match Email,Score,ideal_first_date,short_bio/about_you,best_days_available,best_time_availabilty
0,Corey,coreyross1996@gmail.com,Pritika Sally,tomlinsonhes@gmail.com,78.148648,Meet up & chat at a coffee shop,"Pritika, 26. Work in accounting. Born in Punja...","Friday, Saturday, Sunday","Morning, Afternoon, Evening"
1,Taylor Carlini,taylorcarlini@gmail.com,Jeromy,jerooomyidk@gmail.com,98.518841,Coffee or long walk on a nice day,I’m a therapist that really likes to get out a...,"Saturday, Sunday","Morning, Afternoon, Evening"
2,Suhas,suhas1597@gmail.com,Regan,reganhavens@gmail.com,102.528066,"DIA, mini golf, drinks/cocktails","Nurse practitioner working night shift, dog mo...","Tuesday, Wednesday, Saturday, Sunday","Morning, Afternoon, Evening, Late Night"
3,Will,williamrittenhouse8@gmail.com,KayDee,kd.muhleck@gmail.com,111.081433,An activity rather than just dinner or a movie,I’m pretty active. When it’s nice outside that...,"Monday, Tuesday, Wednesday, Thursday, Friday, ...","Morning, Afternoon, Evening, Late Night"
4,zachary Goldstein,zageagle@gmail.com,Mady Berns,Bernsmadalyn@gmail.com,79.742865,Pickleball and coffee!,My name is Mady! I grew up in Illinois and now...,"Friday, Saturday, Sunday",Evening

In [ ]:
# Clean columns for old matches

older_matches_clean = older_matches_df.rename(columns={
    "Older Match": "Match",
    "Compatibility Score": "Score"
})

# Lookup table from original df
info_lookup = df.drop_duplicates(subset="name").set_index("name")

# Add email columns
older_matches_clean["Person Email"] = older_matches_clean["Person"].map(
    info_lookup["email"]
)

older_matches_clean["Match Email"] = older_matches_clean["Match"].map(
    info_lookup["email"]
)

# Add match details from original df
older_matches_clean["ideal_first_date"] = older_matches_clean["Match"].map(
    info_lookup["ideal_first_date"]
)

older_matches_clean["short_bio/about_you"] = older_matches_clean["Match"].map(
    info_lookup["short_bio/about_you"]
)

older_matches_clean["best_days_available"] = older_matches_clean["Match"].map(
    info_lookup["best_days_available"]
)

older_matches_clean["best_time_availabilty"] = older_matches_clean["Match"].map(
    info_lookup["best_time_availabilty"]
)

# NOW select final columns
older_matches_clean = older_matches_clean[
    [
        "Person",
        "Person Email",
        "Match",
        "Match Email",
        "Score",
        "ideal_first_date",
        "short_bio/about_you",
        "best_days_available",
        "best_time_availabilty"
    ]
]

older_matches_clean.head()

,Person,Person Email,Match,Match Email,Score,ideal_first_date,short_bio/about_you,best_days_available,best_time_availabilty
0,Sam Sovran,sam.sovran@gmail.com,Karen Smith,k.e.smith.1986@gmail.com,100,Coffee or drinks and appetizers,\n\nMoved to Michigan from Georgia in January ...,"Friday, Saturday, Sunday","Afternoon, Evening"
1,Karen Smith,k.e.smith.1986@gmail.com,Vincenzo Francis,francis.vincenzo@gmail.com,100,"Morning gym or long walk, coffee, a delicious ...","\n\n36, travel during the week but home every ...","Friday, Saturday, Sunday","Afternoon, Evening, Late Night"
2,Shayna,waldman.shayna@gmail.com,Vincenzo Francis,francis.vincenzo@gmail.com,100,"Morning gym or long walk, coffee, a delicious ...","\n\n36, travel during the week but home every ...","Friday, Saturday, Sunday","Afternoon, Evening, Late Night"
3,Vigul Desai,viguldesai76@gmail.com,Vincenzo Francis,francis.vincenzo@gmail.com,100,"Morning gym or long walk, coffee, a delicious ...","\n\n36, travel during the week but home every ...","Friday, Saturday, Sunday","Afternoon, Evening, Late Night"
4,Loren Shevitz,8x2dmvyfv9@privaterelay.appleid.com,Karen Smith,k.e.smith.1986@gmail.com,100,Coffee or drinks and appetizers,\n\nMoved to Michigan from Georgia in January ...,"Friday, Saturday, Sunday","Afternoon, Evening"

In [ ]:
# Clean columns for older matches

second_matches_clean = second_pass_df.rename(columns={
    "Second Pass Match": "Match",
    "Compatibility Score": "Score"
})

# Lookup table from original df
info_lookup = df.drop_duplicates(subset="name").set_index("name")

# Add email columns
second_matches_clean["Person Email"] = second_matches_clean["Person"].map(
    info_lookup["email"]
)

second_matches_clean["Match Email"] = second_matches_clean["Match"].map(
    info_lookup["email"]
)

# Add match details from original df
second_matches_clean["ideal_first_date"] = second_matches_clean["Match"].map(
    info_lookup["ideal_first_date"]
)

second_matches_clean["short_bio/about_you"] = second_matches_clean["Match"].map(
    info_lookup["short_bio/about_you"]
)

second_matches_clean["best_days_available"] = second_matches_clean["Match"].map(
    info_lookup["best_days_available"]
)

second_matches_clean["best_time_availabilty"] = second_matches_clean["Match"].map(
    info_lookup["best_time_availabilty"]
)

# NOW select final columns
second_matches_clean = second_matches_clean[
    [
        "Person",
        "Person Email",
        "Match",
        "Match Email",
        "Score",
        "ideal_first_date",
        "short_bio/about_you",
        "best_days_available",
        "best_time_availabilty"
    ]
]

second_matches_clean.head()

,Person,Person Email,Match,Match Email,Score,ideal_first_date,short_bio/about_you,best_days_available,best_time_availabilty
0,Erica Traskos,etraskos11@gmail.com,None,NaN,0.0,NaN,NaN,NaN,NaN
1,Mara Matta,matta.maria.jalil@gmail.com,None,NaN,0.0,NaN,NaN,NaN,NaN
2,Crystal Stewart,crystalnicstewart@gmail.com,None,NaN,0.0,NaN,NaN,NaN,NaN
3,Sam Sovran,sam.sovran@gmail.com,None,NaN,0.0,NaN,NaN,NaN,NaN
4,Karen Smith,k.e.smith.1986@gmail.com,None,NaN,0.0,NaN,NaN,NaN,NaN

In [ ]:
print(second_pass_df.columns)

Index(['Person', 'Second Pass Match', 'Compatibility Score'], dtype='object')

In [ ]:
all_matches_clean = pd.concat([
    main_matches_clean,
    my_top_matches,
    second_matches_clean,
    older_matches_clean
], ignore_index=True)

all_matches_clean.head().reset_index()

info_lookup = df.drop_duplicates(subset="name").set_index("name")

all_matches_clean["Person Ideal First Date"] = all_matches_clean["Person"].map(
    info_lookup["ideal_first_date"]
)

all_matches_clean["Person Bio"] = all_matches_clean["Person"].map(
    info_lookup["short_bio/about_you"]
)

all_matches_clean["Match Ideal First Date"] = all_matches_clean["Match"].map(
    info_lookup["ideal_first_date"]
)

all_matches_clean["Match Bio"] = all_matches_clean["Match"].map(
    info_lookup["short_bio/about_you"]
)

all_matches_clean["Person Age"] = all_matches_clean["Person"].map(
    info_lookup["age"]
)

all_matches_clean["Match Age"] = all_matches_clean["Match"].map(
    info_lookup["age"]
)

all_matches_clean["Match best_days_available"] = all_matches_clean["Match"].map(
    info_lookup["best_days_available"]
)

all_matches_clean["Person best_days_available"] = all_matches_clean["Person"].map(
    info_lookup["best_days_available"]
)

all_matches_clean["Match best_time_availabilty"] = all_matches_clean["Match"].map(
    info_lookup["best_time_availabilty"]
)

all_matches_clean["Person best_time_availabilty"] = all_matches_clean["Person"].map(
    info_lookup["best_time_availabilty"]

)

all_matches_clean["Person city/area"] = all_matches_clean["Person"].map(
    info_lookup["city/area"]
)

all_matches_clean["Match city/area"] = all_matches_clean["Match"].map(
    info_lookup["city/area"]
)

# NOW reorder columns
all_matches_clean = all_matches_clean[
    [
        "Person",
        "Person Email",
        "Person Ideal First Date",
        "Person Bio",
        "Person Age",
        "Person best_days_available",
        "Person best_time_availabilty",
        "Person city/area",

        "Match",
        "Match Email",
        "Match Ideal First Date",
        "Match Bio",
        "Match Age",
        "Match best_days_available",
        "Match best_time_availabilty",
        "Match city/area",



        "Score"
    ]
]

# preview
all_matches_clean.head()

,Person,Person Email,Person Ideal First Date,Person Bio,Person Age,Person best_days_available,Person best_time_availabilty,Person city/area,Match,Match Email,Match Ideal First Date,Match Bio,Match Age,Match best_days_available,Match best_time_availabilty,Match city/area,Score
0,Corey,coreyross1996@gmail.com,Coffee shop,I’m an automotive enthusiast looking to meet p...,29.0,"Friday, Saturday, Sunday",Evening,West Bloomfield,Pritika Sally,tomlinsonhes@gmail.com,Meet up & chat at a coffee shop,"Pritika, 26. Work in accounting. Born in Punja...",26.0,"Friday, Saturday, Sunday","Morning, Afternoon, Evening",Farmington Hills,78.148648
1,Taylor Carlini,taylorcarlini@gmail.com,"Walk, coffee/drinks, mini golf, bowling",Emergency veterinarian who genuinely loves her...,27.0,"Wednesday, Thursday, Saturday, Sunday","Afternoon, Evening, Late Night",Royal oak,Jeromy,jerooomyidk@gmail.com,Coffee or long walk on a nice day,I’m a therapist that really likes to get out a...,29.0,"Saturday, Sunday","Morning, Afternoon, Evening",Royal Oak,98.518841
2,Suhas,suhas1597@gmail.com,A casual cocktail bar or a cafe,Outgoing and easy to get along in his late 20s...,28.0,"Monday, Tuesday, Wednesday, Thursday, Friday, ...","Evening, Late Night",Novi,Regan,reganhavens@gmail.com,"DIA, mini golf, drinks/cocktails","Nurse practitioner working night shift, dog mo...",30.0,"Tuesday, Wednesday, Saturday, Sunday","Morning, Afternoon, Evening, Late Night",Troy,102.528066
3,Will,williamrittenhouse8@gmail.com,Coffee/Drinks,Risk management professional at an automotive ...,28.0,"Tuesday, Thursday, Friday, Saturday, Sunday","Morning, Afternoon, Evening, Late Night",Canton/Plymouth,KayDee,kd.muhleck@gmail.com,An activity rather than just dinner or a movie,I’m pretty active. When it’s nice outside that...,27.0,"Monday, Tuesday, Wednesday, Thursday, Friday, ...","Morning, Afternoon, Evening, Late Night",St. Clair Shores,111.081433
4,zachary Goldstein,zageagle@gmail.com,coffee,32 currently working in the automotive industr...,32.0,"Friday, Saturday, Sunday","Afternoon, Evening, Late Night",Rochester hills,Mady Berns,Bernsmadalyn@gmail.com,Pickleball and coffee!,My name is Mady! I grew up in Illinois and now...,29.0,"Friday, Saturday, Sunday",Evening,Royal Oak,79.742865

In [ ]:
all_matches_clean.columns.tolist()

['Person',
 'Person Email',
 'Person Ideal First Date',
 'Person Bio',
 'Person Age',
 'Person best_days_available',
 'Person best_time_availabilty',
 'Person city/area',
 'Match',
 'Match Email',
 'Match Ideal First Date',
 'Match Bio',
 'Match Age',
 'Match best_days_available',
 'Match best_time_availabilty',
 'Match city/area',
 'Score']

In [ ]:
print(len(all_matches_clean))

206

In [ ]:
# Remove rows where Match is missing
all_matches_clean = all_matches_clean.dropna(
    subset=["Match"]
)

# Remove rows where Match says No Match
all_matches_clean = all_matches_clean[
    all_matches_clean["Match"] != "No Match"
]

# Remove exact duplicate rows
all_matches_clean = all_matches_clean.drop_duplicates()

# Create duplicate-pair key
all_matches_clean["pair_key"] = all_matches_clean.apply(
    lambda row: tuple(sorted([
        str(row["Person"]),
        str(row["Match"])
    ])),
    axis=1
)

# Remove duplicate pairs like A-B and B-A
all_matches_clean = all_matches_clean.drop_duplicates(
    subset=["pair_key"]
)

# Drop helper column
all_matches_clean = all_matches_clean.drop(
    columns=["pair_key"]
)

# FINAL CLEAN TABLE
all_matches_clean = all_matches_clean.drop_duplicates()

# -------------------------
# ADD THIS RIGHT HERE
# -------------------------

# Full table (everyone)
all_matches_full = all_matches_clean.copy()

# Real matches only
match_emails_df = all_matches_full[
    all_matches_full["Match"].notna()
]

match_emails_df = match_emails_df[
    match_emails_df["Match"] != "No Match"
]

# No match people
no_match_df = all_matches_full[
    all_matches_full["Match"].isna()
]

# Preview counts
print("All people:", len(all_matches_full))
print("Matched people:", len(match_emails_df))
print("No match people:", len(no_match_df))

All people: 114
Matched people: 114
No match people: 0

In [ ]:
all_matches_clean.to_csv(r"\\ad.wayne.edu\Users\ex4360\Documents\Blind Date Detroit\Match Rounds\all_matches_clean.csv")

In [ ]:
# Find row index to change ma
pd.set_option("display.max_rows", None)

match_emails_df.reset_index()[[
    "index",
    "Person",
    "Match"
]]

     index               Person              Match
0        0                Corey      Pritika Sally
1        1       Taylor Carlini             Jeromy
2        2                Suhas              Regan
3        3                Will              KayDee
4        4    zachary Goldstein         Mady Berns
5        6      Matt Grunzweig     Madison Harbort
6        7               Keegan   Olivia Patercsak
7        8          Kiara Greer      Julien Medel
8        9         Bryan Fettig     Rhiannon Shook
9       10      Samantha Larson            Carlos
10      11       Dishawn Thiran     Rhiannon Shook
11      12      Melanie Walters   Vincenzo Francis
12      13       Eduardo Cerame              Leila
13      15         Jonah Karson             KayDee
14      16             Vanessa               Nihal
15      17         Fahad Pervez              Marah
16      18          Ana Cedillo         Prashanth
17      20       Spencer Malley               Mark
18      21     Vincenzo Francis   Olivia Patercsak
19      22              Hugo B.              Regan
20      23                James        Emily Howse
21      24                Aaron             Arshya
22      25                 Maya               Alex
23      26                 John       Dani Malina
24      27           Mazen Syed               Kim
25      30               Jeremy   reigan Henderson
26      31         Travis Conte             Amanda
27      32        Lily Robinson         Eric Giles
28      33        Alec Baslock         Emily Howse
29      34             Prabhjit             Arshya
30      35               Amanda             Jeromy
31      36                 Adam        Lily Nguyen
32      39               Justis            Carlos
33      40         Eriyon Adams   Angela Rodriguez
34      41            Sai Zaman         Mady Berns
35      42                 Mark     Danny Ashcraft
36      43        Julian Fascio      Pritika Sally
37      44                 Tony        Lily Nguyen
38      45        Pritika Sally             Tyler
39      47   Shreyas Bharadwaj    reigan Henderson
40      48                Tommy   Angela Rodriguez
41      49                David      Sabina Mustic
42      50          Emily Howse             Puneet
43      51     reigan Henderson              Aldo
44      52             Mitchell      Sabina Mustic
45      53      Madison Harbort       Andrew Fabry
46      54    Brittiney Sempasa               Sean
47      55          Jeff Togger    Diamond Hawkins
48      56              Justin        Jenna Perugi
49      58         Jenna Perugi               Sean
50      60         Spencer Owen       Dani Malina
51      61          Evan Dawson              Marah
52      62              Carlos              Vivien
53      63                Marah              Nihal
54      64     Angela Rodriguez              Aldo
55      65  Jennifer Beltowski          Prashanth
56      69             Nishant               Leila
57      70                 Evan             Vivien
58      71           Prashanth                Kim
59      72             Lisa Sun             Tyler
60      73         Kwame Afrani               Madi
61      75        Matthew Horne               Madi
62      76     Halle Jonassaint   Jonathan Paulino
63      77                Regan               Dave
64      80         Dani Malina                Dave
65      81       Rhiannon Shook             Puneet
66      83                Aldo       MELANIE BETEL
67      84     Olivia Patercsak                Sai
68      85                  Sai        Lucia Sosa
69      86               KayDee       Andrew Fabry
70      88                  Emi        Leonel Cuba
71      89                 Sean        Lucia Sosa
72      90                Halie               Alex
73      95                 Madi        Leonel Cuba
74      96                  Rob      MELANIE BETEL
75      97      Diamond Hawkins  Quinton Lemanski
76     100               Arshya        Nick Hughes
77     103               Vivien     Harjas Dadiyal
78     108                 Kim   Quinton Lemanski
79     109          Lily Nguyen     Ethan Dietrich
80     118        Sabina Mustic        Nick Hughes
81     125           Mady Berns       Andrew Quang
82     139         Eriyon Adams     Rhiannon Shook
83     140         Eriyon Adams        Kiara Greer
84     141         Eriyon Adams             KayDee
85     151   Alejandro Perkins              KayDee
86     157       Ethan Dietrich             KayDee
87     158                 Abhi   Angela Rodriguez
88     160                Nihal   Angela Rodriguez
89     161               Tyler              KayDee
90     162           Eric Giles        Kiara Greer
91     164          Ryjean Reid        Lily Nguyen
92     165     Jonathan Paulino              Regan
93     166       Harjas Dadiyal   Angela Rodriguez
94     167               Jeromy             KayDee
95     168                Leila                Sai
96     170           Kyle Russ      Rhiannon Shook
97     174          Leonel Cuba   Olivia Patercsak
98     176                 Evan     Rhiannon Shook
99     179          Lucia Sosa                 Rob
100    181         Evan D'Silva   reigan Henderson
101    185      Michael Goodwin     Taylor Carlini
102    186         Andrew Quang   reigan Henderson
103    187          Nick Hughes              Regan
104    189                 Alex               Kim
105    190    Quinton Lemanski              KayDee
106    193        MELANIE BETEL   Vincenzo Francis
107    199               Ashwin             KayDee
108    200           Sam Sovran        Karen Smith
109    201          Karen Smith   Vincenzo Francis
110    202               Shayna   Vincenzo Francis
111    203          Vigul Desai   Vincenzo Francis
112    204        Loren Shevitz        Karen Smith
113    205          Ryjean Reid        Karen Smith

In [ ]:
#Change Eriyon's bio
match_emails_df.loc[
    match_emails_df["Person"] == "Eriyon Adams",
    "Person Bio"
] = """
Easygoing and driven guy who enjoys staying active, trying new things, and meeting new people. Into fitness, good conversations, social events, and keeping life fun and low pressure.
"""

In [ ]:
# change Eriyon match
match_emails_df.at[81, "Match"] = "Regan"

# lookup
info_lookup = df.drop_duplicates(subset="name").set_index("name")

# update match details
match_emails_df.at[81, "Match Email"] = info_lookup.at["Regan", "email"]
match_emails_df.at[81, "Match Bio"] = info_lookup.at["Regan", "short_bio/about_you"]
match_emails_df.at[81, "Match Age"] = info_lookup.at["Regan", "age"]
match_emails_df.at[81, "Match Ideal First Date"] = info_lookup.at["Regan", "ideal_first_date"]
match_emails_df.at[81, "Match city/area"] = info_lookup.at["Regan", "city/area"]

C:\Users\ex4360\AppData\Local\Temp\ipykernel_11856\1668774350.py:10: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '30' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  match_emails_df.at[81, "Match Age"] = info_lookup.at["Regan", "age"]

In [ ]:
match_emails_df.loc[33]

Person                                                               Eriyon Adams
Person Email                                              eriyonadams10@gmail.com
Person Ideal First Date                   Activity,Coffee,Drink, something simple
Person Bio                      \nEasygoing and driven guy who enjoys staying ...
Person Age                                                                   26.0
Person best_days_available          Wednesday, Thursday, Friday, Saturday, Sunday
Person best_time_availabilty                       Afternoon, Evening, Late Night
Person city/area                                       Sterling Heights/Royal Oak
Match                                                            Angela Rodriguez
Match Email                                           angierodriguez017@gmail.com
Match Ideal First Date          Drinks and Apps on a patio :) pretty much anyt...
Match Bio                       Moved to Michigan from South Carolina 3 years ...
Match Age                                                                    23.0
Match best_days_available             Tuesday, Thursday, Friday, Saturday, Sunday
Match best_time_availabilty                        Afternoon, Evening, Late Night
Match city/area                                                       Franklin Mi
Score                                                                   92.312685
Name: 33, dtype: object

In [ ]:
#Manual adding people
new_match = match_emails_df.iloc[0].copy()

new_match["Person"] = "Erica Traskos"
new_match["Match"] = "Alex"

info_lookup = df.set_index("name")

# person info
new_match["Person Email"] = info_lookup.at[
    "Erica Traskos",
    "email"
]

# match info
new_match["Match Email"] = info_lookup.at[
    "Alex",
    "email"
]

new_match["Match Bio"] = info_lookup.at[
    "Alex",
    "short_bio/about_you"
]

new_match["Match Age"] = info_lookup.at[
    "Alex",
    "age"
]


match_emails_df = pd.concat(
[match_emails_df, pd.DataFrame([new_match])],
ignore_index=True
)

In [ ]:
#Check to see if match is added
match_emails_df[
    match_emails_df["Person"] == "Erica Traskos"
][[
    "Person",
    "Person Email",
    "Match",
    "Match Email"
]]

            Person          Person Email Match               Match Email
114  Erica Traskos  etraskos11@gmail.com  Alex  alexander.rea5@yahoo.com

In [ ]:
# Removing/adding Lansing girl matches

# Clean names
df["name"] = df["name"].astype(str).str.strip()
match_emails_df["Person"] = match_emails_df["Person"].astype(str).str.strip()
match_emails_df["Match"] = match_emails_df["Match"].astype(str).str.strip()

# Remove her old matches
match_emails_df = match_emails_df[
    match_emails_df["Person"] != "Rhiannon Shook"
]

# Find Aldo's exact row
aldo_row = df[
    df["name"].str.contains("Aldo", case=False, na=False)
].iloc[0]

rhiannon_row = df[
    df["name"] == "Rhiannon Shook"
].iloc[0]

# Copy template row
new_match1 = match_emails_df.iloc[0].copy()

# Add new match
new_match1["Person"] = "Rhiannon Shook"
new_match1["Match"] = aldo_row["name"]

new_match1["Person Email"] = rhiannon_row["email"]
new_match1["Match Email"] = aldo_row["email"]

new_match1["Match Bio"] = aldo_row["short_bio/about_you"]
new_match1["Match Age"] = aldo_row["age"]

# Add row back to match_emails_df
match_emails_df = pd.concat(
    [match_emails_df, pd.DataFrame([new_match1])],
    ignore_index=True
)

# Check it
match_emails_df[
    match_emails_df["Person"] == "Rhiannon Shook"
][["Person", "Person Email", "Match", "Match Email", "Match Age"]]

,Person,Person Email,Match,Match Email,Match Age
114,Rhiannon Shook,rhiannonelaine17@gmail.com,Aldo,aldo.j.cavazos.l@gmail.com,30.0

In [ ]:
# Second match for Rhiannon

new_match2 = match_emails_df.iloc[0].copy()

# Find second guy
second_guy = df[
    df["name"].str.contains("Suhas", case=False, na=False)
].iloc[0]

# Rhiannon row
rhiannon_row = df[
    df["name"] == "Rhiannon Shook"
].iloc[0]

# Fill info
new_match2["Person"] = "Rhiannon Shook"
new_match2["Match"] = second_guy["name"]

new_match2["Person Email"] = rhiannon_row["email"]
new_match2["Match Email"] = second_guy["email"]

new_match2["Match Bio"] = second_guy["short_bio/about_you"]
new_match2["Match Age"] = second_guy["age"]

# Add row
match_emails_df = pd.concat(
    [match_emails_df, pd.DataFrame([new_match2])],
    ignore_index=True
)

# Check
match_emails_df[
    match_emails_df["Person"] == "Rhiannon Shook"
][["Person", "Match"]]

match_emails_df = match_emails_df.drop_duplicates(
    subset=["Person", "Match"]
)

In [ ]:
# Matching emails test

sent_pairs = set()

with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:

    smtp.login(sender_email, app_password)

    def first_name(full_name):
        return str(full_name).split()[0]

    # clean names just in case
    df["name"] = df["name"].astype(str).str.strip()
    match_emails_df["Person"] = match_emails_df["Person"].astype(str).str.strip()
    match_emails_df["Match"] = match_emails_df["Match"].astype(str).str.strip()

    for index, row in match_emails_df.iterrows():

        person_name = row["Person"]
        match_name = row["Match"]
        score = row["Score"]

        person_first = first_name(person_name)
        match_first = first_name(match_name)

        if pd.isna(match_name) or score == 0:
            continue

        pair = tuple(sorted([person_name, match_name]))

        if pair in sent_pairs:
            continue

        sent_pairs.add(pair)

        # find people safely
        person_rows = df[df["name"] == person_name]
        match_rows = df[df["name"] == match_name]

        if person_rows.empty:
            print("Missing person in df:", person_name)
            continue

        if match_rows.empty:
            print("Missing match in df:", match_name)
            continue

        person = person_rows.iloc[0]
        match = match_rows.iloc[0]

        shared_days = set(str(person["best_days_available"]).split(",")).intersection(
            set(str(match["best_days_available"]).split(","))
        )

        shared_times = set(str(person["best_time_availabilty"]).split(",")).intersection(
            set(str(match["best_time_availabilty"]).split(","))
        )

        shared_days_text = ", ".join(shared_days)
        shared_times_text = ", ".join(shared_times)

        shared_days_output = (
            f"Shared Days: {shared_days_text}"
            if shared_days_text
            else "Shared Days: No overlapping days listed"
        )

        shared_times_output = (
            f"Shared Times: {shared_times_text}"
            if shared_times_text
            else "Shared Times: No overlapping times listed"
        )

        msg = EmailMessage()

        msg["Subject"] = "Your Blind Date Match"
        msg["From"] = sender_email
        msg["To"] = person["email"]
        msg["Cc"] = match["email"]

        email_body = f"""
Hey {person_first} and {match_first},

You two matched!

Shared Availability:
{shared_days_output}
{shared_times_output}

About {person_first}:

Ideal First Date:
{person["ideal_first_date"]}

Age: {person["age"]}
Area: {person["city/area"]}

Bio:
{person["short_bio/about_you"]}

About {match_first}:

Ideal First Date:
{match["ideal_first_date"]}

Age: {match["age"]}
Area: {match["city/area"]}

Bio:
{match["short_bio/about_you"]}

Feel free to reply to this email and connect.

Please be respectful and meet in public places.

- Blind Matchmaking Project
"""

        msg.set_content(email_body.strip())

        print(email_body)
        print("=" * 80)
        print(f"Previewed match email to {person_first} and {match_first}")

Hey Corey and Pritika,

You two matched!

Shared Availability:
Shared Days:  Sunday,  Saturday, Friday
Shared Times: No overlapping times listed

About Corey:

Ideal First Date:
Coffee shop

Age: 29
Area: West Bloomfield

Bio:
I’m an automotive enthusiast looking to meet people that are in to cars and to build a relationship with them. Very music oriented as well.

About Pritika:

Ideal First Date:
Meet up & chat at a coffee shop

Age: 26
Area: Farmington Hills

Bio:
Pritika, 26. Work in accounting. Born in Punjab, India, studied in Australia, then moved to the US for my Master's in Finance almost 4 years ago. Love travelling and music, always up for trying new things. Ready to find my person and build a life together. Looking for someone ambitious and adventurous who loves trying new cuisines, travel destinations, and experiences. I'm tall (almost 5'10), and would love to meet someone who's the same height or taller.

Feel free to reply to this email and connect.

Please be respectful and meet in public places.

- Blind Matchmaking Project

================================================================================
Previewed match email to Corey and Pritika

Hey Taylor and Jeromy,

You two matched!

Shared Availability:
Shared Days:  Sunday
Shared Times:  Evening

About Taylor:

Ideal First Date:
Walk, coffee/drinks, mini golf, bowling

Age: 27
Area: Royal oak

Bio:
Emergency veterinarian who genuinely loves her work. Dog parent who walks her pup regularly. Coffee shop enthusiast always on the hunt for new spots. Spontaneous traveler who books flights to lift her mood and wants a travel buddy for her next trip.

About Jeromy:

Ideal First Date:
Coffee or long walk on a nice day

Age: 29
Area: Royal Oak

Bio:
I’m a therapist that really likes to get out and try new foods or new shopping stores. I also just love walking around too and people watch or just sit and appreciate silence.

Feel free to reply to this email and connect.

Please be respectful and meet in public places.

- Blind Matchmaking Project

================================================================================
Previewed match email to Taylor and Jeromy

Hey Suhas and Regan,

You two matched!

Shared Availability:
Shared Days:  Sunday,  Wednesday,  Saturday
Shared Times:  Late Night

About Suhas:

Ideal First Date:
A casual cocktail bar or a cafe

Age: 28
Area: Novi

Bio:
Outgoing and easy to get along in his late 20s looking forward to exploring life

About Regan:

Ideal First Date:
DIA, mini golf, drinks/cocktails

Age: 30
Area: Troy

Bio:
Nurse practitioner working night shift, dog mom, love to try new things, very curious and down for a spontaneous adventure, lover of all things whimsical.

Feel free to reply to this email and connect.

Please be respectful and meet in public places.

- Blind Matchmaking Project

================================================================================
Previewed match email to Suhas and Regan

Hey Will and KayDee,

You two matched!

Shared Availability:
Shared Days:  Thursday,  Sunday,  Friday,  Saturday
Shared Times:  Late Night,  Evening,  Afternoon, Morning

About Will:

Ideal First Date:
Coffee/Drinks

Age: 28
Area: Canton/Plymouth

Bio:
Risk management professional at an automotive company. Volunteer firefighter and EMT. I stay active with competitive volleyball, workouts, and weekends at the lake or beach. Love country concerts and outdoor adventures.

About KayDee:

Ideal First Date:
An activity rather than just dinner or a movie

Age: 27
Area: St. Clair Shores

Bio:
I’m pretty active. When it’s nice outside that’s where I’d rather be. I’m a nightshift ER nurse so my schedules pretty dependent on when I work so I often run on little sleep and lots of coffee.

Feel free to reply to this email and connect.

Please be respectful and meet in public places.

- Blind Matchmaking Project

================================================================================
Previewed match email to Will and KayDee

Hey zachary and Mady,

You two matched!

Shared Availability:
Shared Days:  Sunday,  Saturday, Friday
Shared Times: No overlapping times listed

About zachary:

Ideal First Date:
coffee

Age: 32
Area: Rochester hills

Bio:
32 currently working in the automotive industry.  on the weekends I like to ski, working on diy projects,  going to races or car&coffee. favorite place outside of Michigan is Colorado

About Mady:

Ideal First Date:
Pickleball and coffee!

Age: 29
Area: Royal Oak

Bio:
My name is Mady! I grew up in Illinois and now live in royal oak. I am a speech language pathologist working with children with a wide age range. I love to travel, meet dogs, drink coffee, workout and pickleball!

Feel free to reply to this email and connect.

Please be respectful and meet in public places.

- Blind Matchmaking Project

================================================================================
Previewed match email to zachary and Mady

Hey Matt and Madison,

You two matched!

Shared Availability:
Shared Days:  Thursday,  Sunday,  Friday,  Saturday
Shared Times: No overlapping times listed

About Matt:

Ideal First Date:
Drinks

Age: 28
Area: Royal Oak

Bio:
I’m interested in anything automotive and am big on the outdoors with hunting, shooting, fishing, hiking, and camping

About Madison:

Ideal First Date:
 ideal first date would be grabbing drinks on a patio or dinner. A workout could also be fun!

Age: 29
Area: Birmingham

Bio:
living in Birmingham, MI. I am outgoing, friendly, and want someone who is intentional with a good sense of humor, social, and likes to make plans and go out.

Feel free to reply to this email and connect.

Please be respectful and meet in public places.

- Blind Matchmaking Project

================================================================================
Previewed match email to Matt and Madison

Hey Keegan and Olivia,

You two matched!

Shared Availability:
Shared Days:  Thursday,  Friday,  Saturday, Monday
Shared Times: No overlapping times listed

About Keegan:

Ideal First Date:
Colored pencils in the park

Age: 33
Area: Royal Oak

Bio:
Lawyer in civil rights and criminal defense;  sensitive and intelligent; love playful, thoughtful, creative people and things

About Olivia:

Ideal First Date:
Simple coffee or drinks to see if we can even carry a conversation

Age: 32
Area: Clarkston

Bio:
I spend my time at my job as a researcher, with  my dog, playing with my local community band, or working in my garden. My friends and family say I’m thoughtful, silly, and calm.

Feel free to reply to this email and connect.

Please be respectful and meet in public places.

- Blind Matchmaking Project

================================================================================
Previewed match email to Keegan and Olivia

Hey Kiara and Julien,

You two matched!

Shared Availability:
Shared Days:  Sunday,  Friday,  Saturday, Monday
Shared Times:  Evening

About Kiara:

Ideal First Date:
Baseball game, dinner, sunset walk with pup

Age: 22
Area: Clarkston mi

Bio:
I’m 22, brown hair, going to school for teaching, love my friends and family

About Julien:

Ideal First Date:
Going out to eat somewhere. Maybe get ice cream or explore the city

Age: 24
Area: Berkley

Bio:
I’m a soon to be college graduate hoping to find someone to be able to spend time with. I love supporting my Detroit teams, online surfing, experiencing new shows and stuff to do, and getting to be with family.

Feel free to reply to this email and connect.

Please be respectful and meet in public places.

- Blind Matchmaking Project

================================================================================
Previewed match email to Kiara and Julien

Hey Bryan and Rhiannon,

You two matched!

Shared Availability:
Shared Days:  Sunday,  Saturday
Shared Times:  Evening, Afternoon

About Bryan:

Ideal First Date:
Drinks or coffee maybe light appetizers but no dinners for first date

Age: 30
Area: Madison Heights Royal oak

Bio:
Renewable energy professional and MBA student. Love traveling, especially up north, and I'm on a weight loss journey. Huge Detroit fan, avid reader, and easygoing. Looking for someone with shared values for a serious relationship, but open to casual connections too.

About Rhiannon:

Ideal First Date:
Any activity where we’re able to talk and get to know each other like maybe grab drinks or dinner, go for a walk, or go to a sports game, or maybe a local event.

Age: 25
Area: Lansing

Bio:
Michigan State grad (2023) with a BA in Interior Design. Now a full-time real estate marketing director and freelance designer. Spontaneous and always up for trying something new. Love the outdoors and dreaming up new adventures. Proud to have achieved a lot early own a house, cat named Phillip, and have done a lot of personal growth work. Looking for someone to complement my life and build something meaningful together while we chase our individual goals. Go Green! 🍴

Feel free to reply to this email and connect.

Please be respectful and meet in public places.

- Blind Matchmaking Project

================================================================================
Previewed match email to Bryan and Rhiannon

Hey Samantha and Carlos,

You two matched!

Shared Availability:
Shared Days: No overlapping days listed
Shared Times:  Late Night,  Evening

About Samantha:

Ideal First Date:
Activity-ish. Any type of competitive activity, adventure, or learning/trying something new!  Not interested in any “dinner & drinks” vibes.

Age: 25
Area: Holly, Michigan

Bio:
Social worker helping older adults with disabilities. Homeowner in Holly with three German Shepherds I train, they're my world. Play softball nationally (SS on an Ohio team). Not into partying, but I'll sip tequila occasionally. I'd rather have deep conversations than small talk. Into landscaping, gardening, reading, and learning about the brain. Love karaoke and staying active. Looking for someone real, passionate, and willing to grow together.



About Carlos:

Ideal First Date:
Coffee or drinks

Age: 31
Area: Oak park

Bio:
Introverted home body that loves to read, go for walks, listen to music, go to the gym, and try out new places

Feel free to reply to this email and connect.

Please be respectful and meet in public places.

- Blind Matchmaking Project

================================================================================
Previewed match email to Samantha and Carlos

Hey Dishawn and Rhiannon,

You two matched!

Shared Availability:
Shared Days:  Sunday,  Friday
Shared Times:  Late Night,  Evening, Afternoon

About Dishawn:

Ideal First Date:
Ice cream and a walk

Age: 27
Area: Troy/metro Detroit

Bio:
Engineer and businessman building a company. I stay active, exercise, and play casual sports. Have traveled the world and have the stories to show for it. Looking for a partner to enjoy life's adventures with and build something meaningful together.



About Rhiannon:

Ideal First Date:
Any activity where we’re able to talk and get to know each other like maybe grab drinks or dinner, go for a walk, or go to a sports game, or maybe a local event.

Age: 25
Area: Lansing

Bio:
Michigan State grad (2023) with a BA in Interior Design. Now a full-time real estate marketing director and freelance designer. Spontaneous and always up for trying something new. Love the outdoors and dreaming up new adventures. Proud to have achieved a lot early own a house, cat named Phillip, and have done a lot of personal growth work. Looking for someone to complement my life and build something meaningful together while we chase our individual goals. Go Green! 🍴

Feel free to reply to this email and connect.

Please be respectful and meet in public places.

- Blind Matchmaking Project

================================================================================
Previewed match email to Dishawn and Rhiannon

Hey Melanie and Vincenzo,

You two matched!

Shared Availability:
Shared Days:  Sunday,  Saturday
Shared Times:  Evening

About Melanie:

Ideal First Date:
Coffee/Tea, walk at a park, something where we can talk easily

Age: 30
Area: Troy, MI

Bio:
Three words to describe me are playful, loyal, and thoughtful. I grew up in Michigan but moved away to live in Paris, France, Chicago, and San Francisco. I'm a very open-minded, liberal person and would appreciate someone with similar values. I'm big on balance: I love big adventures like traveling and discovering new cities but also love the small daily adventures like finding a new favorite local Cafe, cooking at home, or enjoying a cup of tea and a good book. I consider myself an ambivert: I might be a little shy when first meeting but once I get to know you I open up quickly. Some of my main hobbies are yoga, hiking, walking, weight lifting, reading, watching TV and movies and crafting. I am not big into night life or drinking and prefer spending my time at activity based events.

About Vincenzo:

Ideal First Date:
Morning gym or long walk, coffee, a delicious and healthy lunch, followed by a day at the beach. Grill and campfire for dinner and relax with a book

Age: 36
Area: Oak Park

Bio:


36, travel during the week but home every weekend. Love physical activity, healthy living, and balance it with some nightlife. Into reading and audiobooks, Star Wars, and ultimate frisbee when time allows. Occasional marijuana, social drinker. Love spending time with close friends and family. Christian who believes faith is shown through action and how you treat others. Committed to my career.

Feel free to reply to this email and connect.

Please be respectful and meet in public places.

- Blind Matchmaking Project

================================================================================
Previewed match email to Melanie and Vincenzo

Hey Eduardo and Leila,

You two matched!

Shared Availability:
Shared Days:  Saturday
Shared Times: No overlapping times listed

About Eduardo:

Ideal First Date:
Arcade/Activity

Age: 34
Area: Macomb Township

Bio:
Robotics engineer interested in cosplay, 3D printing, gaming, and science.

About Leila:

Ideal First Date:
Outdoor activities

Age: 34
Area: Metro Detroit

Bio:
Lebanese Muslim looking for similar

Feel free to reply to this email and connect.

Please be respectful and meet in public places.

- Blind Matchmaking Project

================================================================================
Previewed match email to Eduardo and Leila

Hey Jonah and KayDee,

You two matched!

Shared Availability:
Shared Days:  Thursday, Monday,  Friday,  Sunday,  Saturday,  Wednesday
Shared Times:  Late Night,  Evening,  Afternoon, Morning

About Jonah:

Ideal First Date:
Coffee shop, dinner or drinks, farmers market, I’m very open minded

Age: 25
Area: Farmington Hills

Bio:
Recently graduated with my MSW, looking to get more into the dating scene, I love having fun and new experiences.

About KayDee:

Ideal First Date:
An activity rather than just dinner or a movie

Age: 27
Area: St. Clair Shores

Bio:
I’m pretty active. When it’s nice outside that’s where I’d rather be. I’m a nightshift ER nurse so my schedules pretty dependent on when I work so I often run on little sleep and lots of coffee.

Feel free to reply to this email and connect.

Please be respectful and meet in public places.

- Blind Matchmaking Project

================================================================================
Previewed match email to Jonah and KayDee

Hey Vanessa and Nihal,

You two matched!

Shared Availability:
Shared Days: No overlapping days listed
Shared Times: No overlapping times listed

About Vanessa:

Ideal First Date:
We go out dancing

Age: 26
Area: Waterford

Bio:
nan

About Nihal:

Ideal First Date:
Meet at a cafe, get to know each other, fun activity later

Age: 28
Area: Troy

Bio:
I’m a pretty open guy, love clear communication and I enjoy exploring different cultures and cuisines. I have interests in horror movies, anime, soccer and love playing board games. Fairly fit and prefer the outdoor life.

Feel free to reply to this email and connect.

Please be respectful and meet in public places.

- Blind Matchmaking Project

================================================================================
Previewed match email to Vanessa and Nihal

Hey Fahad and Marah,

You two matched!

Shared Availability:
Shared Days:  Thursday,  Tuesday, Monday,  Friday,  Sunday,  Saturday,  Wednesday
Shared Times:  Evening, Afternoon

About Fahad:

Ideal First Date:
Dinner over a candlelight dinner

Age: 26
Area: Northville

Bio:
Passionate about exploring the world, whipping up delicious meals, indulging in retail therapy, capturing beautiful moments through photography, and embarking on new adventures. Currently a year medical student

About Marah:

Ideal First Date:
Surprise me

Age: 26
Area: Clinton Twp

Bio:
Name means "fun" in Arabic. 5'5, brunette, Middle Eastern, and Muslim. Love joking around but also deep 2am conversations. Like someone who communicates openly, laughs easily, and tries new things. Recently getting into outdoor hobbies. Don't smoke, don't drink myself but fine with someone who does casually. Looking for good energy, emotional awareness, and someone who knows when to be playful and when to be real. 🙂

Feel free to reply to this email and connect.

Please be respectful and meet in public places.

- Blind Matchmaking Project

================================================================================
Previewed match email to Fahad and Marah

Hey Ana and Prashanth,

You two matched!

Shared Availability:
Shared Days:  Friday
Shared Times:  Late Night

About Ana:

Ideal First Date:
Walk in a park and then boba tea

Age: 29
Area: Oak Park

Bio:
I enjoy spending time with friend, volunteering, and finding joy in the little things. Looking for someone kind, grounded, and fun to share good conversations and experiences with.

About Prashanth:

Ideal First Date:
Art gallery

Age: 32
Area: Metro Detroit

Bio:
Daydreamer

Feel free to reply to this email and connect.

Please be respectful and meet in public places.

- Blind Matchmaking Project

================================================================================
Previewed match email to Ana and Prashanth

Hey Spencer and Mark,

You two matched!

Shared Availability:
Shared Days:  Wednesday,  Tuesday, Monday,  Saturday
Shared Times:  Late Night, Evening

About Spencer:

Ideal First Date:
Some sort of live music

Age: 29
Area: Ann Arbor

Bio:


Music teacher by day, adventure seeker by night and weekend. Happy at concerts, on bike trails, or watching Tigers games. Love good conversation, people who can laugh at themselves, and trying new things.

About Mark:

Ideal First Date:
Dinner or a walk

Age: 29
Area: West Bloomfield

Bio:
Mark, 29. Behavior Technician and passionate dancer and cosplayer. Nerd and pop culture lover. Value genuine connections in both friendships and romance. Looking for something serious and monogamous, but open to shorter-term dating and friendships too.



Feel free to reply to this email and connect.

Please be respectful and meet in public places.

- Blind Matchmaking Project

================================================================================
Previewed match email to Spencer and Mark

Hey Vincenzo and Olivia,

You two matched!

Shared Availability:
Shared Days:  Saturday
Shared Times: No overlapping times listed

About Vincenzo:

Ideal First Date:
Morning gym or long walk, coffee, a delicious and healthy lunch, followed by a day at the beach. Grill and campfire for dinner and relax with a book

Age: 36
Area: Oak Park

Bio:



In [ ]:
# TEST MATCH EMAIL TO YOURSELF

with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:

    smtp.login(sender_email, app_password)

    def first_name(full_name):
        return str(full_name).split()[0]

    # clean names
    df["name"] = df["name"].astype(str).str.strip()
    match_emails_df["Person"] = match_emails_df["Person"].astype(str).str.strip()
    match_emails_df["Match"] = match_emails_df["Match"].astype(str).str.strip()

    # grab first match row
    row = match_emails_df.iloc[0]

    person_name = row["Person"]
    match_name = row["Match"]
    score = row["Score"]

    person_first = first_name(person_name)
    match_first = first_name(match_name)

    person = df[df["name"] == person_name].iloc[0]
    match = df[df["name"] == match_name].iloc[0]

    # shared availability
    shared_days = set(
        str(person["best_days_available"]).split(",")
    ).intersection(
        set(str(match["best_days_available"]).split(","))
    )

    shared_times = set(
        str(person["best_time_availabilty"]).split(",")
    ).intersection(
        set(str(match["best_time_availabilty"]).split(","))
    )

    shared_days_text = ", ".join(shared_days)
    shared_times_text = ", ".join(shared_times)

    shared_days_output = (
        f"Shared Days: {shared_days_text}"
        if shared_days_text
        else "Shared Days: No overlapping days listed"
    )

    shared_times_output = (
        f"Shared Times: {shared_times_text}"
        if shared_times_text
        else "Shared Times: No overlapping times listed"
    )

    # create email
    msg = EmailMessage()

    msg["Subject"] = "TEST - Your Blind Date Match"
    msg["From"] = sender_email

    # SEND TO YOURSELF
    msg["To"] = "blindmatchdetroit@gmail.com"

    email_body = f"""
Hey {person_first} and {match_first},

You two matched!

Shared Availability:
{shared_days_output}
{shared_times_output}

About {person_first}:

Ideal First Date:
{person["ideal_first_date"]}

Age: {person["age"]}
Area: {person["city/area"]}

Bio:
{person["short_bio/about_you"]}

About {match_first}:

Ideal First Date:
{match["ideal_first_date"]}

Age: {match["age"]}
Area: {match["city/area"]}

Bio:
{match["short_bio/about_you"]}

Feel free to reply to this email and connect.

Please be respectful and meet in public places.

- Blind Matchmaking Project
"""

    msg.set_content(email_body.strip())

    smtp.send_message(msg)

    print("Test email sent successfully to yourself.")

Test email sent successfully to yourself.

In [ ]:
#test no match table
print(len(no_match_df))
no_match_df.head()

28

,timestamp,name,email,age,gender,city/area,interested_in,relationship_goal,preferred_age_range,interests,...,short_bio/about_you,best_days_available,best_time_availabilty,"i_understand:\n\n•_matches_are_not_guaranteed__\n•_this_is_an_experimental_matchmaking_project__\n•_i_am_responsible_for_my_own_safety_and_interactions__\n•_first_meetings_should_happen_in_public_places__\n•_if_matched,_my_email_may_be_shared_with_my_match_for_communication_purposes__\n\nprivacy_notice\n\nyour_information_will_only_be_used_for_this_matchmaking_project_and_will_not_be_shared_publicly._responses_will_remain_private,_and_only_necessary_information_may_be_shared_with_a_match_for_communication_purposes._if_you_would_like_your_information_removed_at_any_time,_please_let_me_know.",email_address,city_clean,min_age,max_age,combined_text,county_clean
14,5/14/2026 15:04:42,Mara Matta,matta.maria.jalil@gmail.com,30.0,Women,Royal Oak,"Men, Women",Open to Either,"27–31, 32–36","Gym, Travel, Reading, Hiking, Music",...,"\n\nInto rock climbing, aerial arts, fire eati...","Monday, Friday, Saturday, Sunday","Evening, Late Night",Yes,matta.maria.jalil@gmail.com,royal oak,27,36,"Gym, Travel, Reading, Hiking, Music \n\nInto r...",oakland
19,5/14/2026 15:37:19,Crystal Stewart,crystalnicstewart@gmail.com,26.0,Women,Detroit (West Village),"Men, Women",Open to Either,"22–26, 27–31","Movies, Travel, Food, Sports, Reading, Hiking,...",...,"\r\n\r\nDetroit native, 26. Occidental College...","Monday, Wednesday, Friday, Saturday","Morning, Afternoon, Evening",Yes,crystalnicstewart@gmail.com,detroit (west village),22,31,"Movies, Travel, Food, Sports, Reading, Hiking,...",unknown
46,5/18/2026 8:32:36,Danny Ashcraft,dashcraftjr@gmail.com,29.0,Men,Ferndale,Men,Serious Relationship,27–31,"Movies, Travel, Food, Sports, Reading, Gaming,...",...,"I work full time as a Data Manager, I’m a spor...","Friday, Saturday","Evening, Late Night",Yes,dashcraftjr@gmail.com,ferndale,27,31,"Movies, Travel, Food, Sports, Reading, Gaming,...",oakland
59,5/18/2026 14:57:55,Sola Mewha,solamewha97@gmail.com,25.0,Women,Royal Oak,Women,Serious Relationship,27–31,"Gym, Sports, Music",...,My name is Sola and I love learning to love li...,"Thursday, Sunday",Evening,Yes,solamewha97@gmail.com,royal oak,27,31,"Gym, Sports, Music My name is Sola and I love ...",oakland
67,5/19/2026 11:50:12,Sara Walkup,sara.walkup@gmail.com,43.0,Women,Detroit,Men,Open to Either,36+,"Gym, Travel, Food, Sports, Hiking, Music, Nigh...",...,Just moved back to Michigan after 20 years in ...,"Monday, Tuesday, Wednesday, Thursday, Friday","Afternoon, Evening",Yes,sara.walkup@gmail.com,detroit,36,36,"Gym, Travel, Food, Sports, Hiking, Music, Nigh...",wayne

In [ ]:
# Rebulid
no_match_df = all_matches_full[
    (all_matches_full["Match"].isna()) |
    (all_matches_full["Match"] == "No Match")
]

print(len(no_match_df))
no_match_df.head()

0

Empty DataFrame
Columns: [Person, Person Email, Person Ideal First Date, Person Bio, Person Age, Person best_days_available, Person best_time_availabilty, Person city/area, Match, Match Email, Match Ideal First Date, Match Bio, Match Age, Match best_days_available, Match best_time_availabilty, Match city/area, Score]
Index: []

In [ ]:
matched_people = set(match_emails_df["Person"])

no_match_df = df[
    ~df["name"].isin(matched_people)
]

no_match_df[[
    "name",
    "email"
]]

                   name                         email
14           Mara Matta   matta.maria.jalil@gmail.com
19      Crystal Stewart   crystalnicstewart@gmail.com
46       Danny Ashcraft         dashcraftjr@gmail.com
59           Sola Mewha         solamewha97@gmail.com
67          Sara Walkup         sara.walkup@gmail.com
68           Samantha S           sjstover7@gmail.com
74              Natalie             ntalife@gmail.com
82                Maria             menea13@gmail.com
93   Eyvaughn Standifer   standifereyvaughn@gmail.com
104        Sarah Dooley          sedooley@comcast.net
106              Lauren          lflorkey@comcast.net
107               Brian           bsbrogs05@yahoo.com
110      Lindsay Rogers      lindsayfrogers@gmail.com
112                Niki        nikiboivin09@yahoo.com
114            Michelle    michelleserra73@icloud.com
115               Lissa          elissalund@gmail.com
117        Julien Medel            asdmedel@gmail.com
120                Katy         kmcgarry22@adrian.edu
121         Isha Oberoi        isha.ross187@gmail.com
122               Edona    edona.haziri88@hotmail.com
127              Nikohl        nikohlsands@gmail.comh
130                Dave         Spedmonds47@gmail.com
131        Andrew Fabry            afabry@comcast.net
133              Alissa    alissa.curtis518@gmail.com
134              Puneet      testsubject273@gmail.com
135               Terri          terriswing@yahoo.com
136     Samantha Jacobs  samantha.jacobs920@gmail.com
137                Kate              kwcady@gmail.com

In [ ]:
# Find row index to change ma
pd.set_option("display.max_rows", None)

no_match_df.reset_index()[[
    "index",
    "name",
    "email"
]]

    index                name                         email
0      14          Mara Matta   matta.maria.jalil@gmail.com
1      19     Crystal Stewart   crystalnicstewart@gmail.com
2      46      Danny Ashcraft         dashcraftjr@gmail.com
3      59          Sola Mewha         solamewha97@gmail.com
4      67         Sara Walkup         sara.walkup@gmail.com
5      68          Samantha S           sjstover7@gmail.com
6      74             Natalie             ntalife@gmail.com
7      82               Maria             menea13@gmail.com
8      93  Eyvaughn Standifer   standifereyvaughn@gmail.com
9     104        Sarah Dooley          sedooley@comcast.net
10    106              Lauren          lflorkey@comcast.net
11    107               Brian           bsbrogs05@yahoo.com
12    110      Lindsay Rogers      lindsayfrogers@gmail.com
13    112                Niki        nikiboivin09@yahoo.com
14    114            Michelle    michelleserra73@icloud.com
15    115               Lissa          elissalund@gmail.com
16    117        Julien Medel            asdmedel@gmail.com
17    120                Katy         kmcgarry22@adrian.edu
18    121         Isha Oberoi        isha.ross187@gmail.com
19    122               Edona    edona.haziri88@hotmail.com
20    127              Nikohl        nikohlsands@gmail.comh
21    130                Dave         Spedmonds47@gmail.com
22    131        Andrew Fabry            afabry@comcast.net
23    133              Alissa    alissa.curtis518@gmail.com
24    134              Puneet      testsubject273@gmail.com
25    135               Terri          terriswing@yahoo.com
26    136     Samantha Jacobs  samantha.jacobs920@gmail.com
27    137                Kate              kwcady@gmail.com

In [ ]:
print(len(no_match_df))

19

In [ ]:
# No match email preview

with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:

    smtp.login(sender_email, app_password)

    # helper function
    def first_name(full_name):

        return str(full_name).split()[0]

    # clean names
    df["name"] = df["name"].astype(str).str.strip()

    for index, row in no_match_df.iterrows():

        person_name = row["name"]

        msg = EmailMessage()

        msg["Subject"] = "Blind Matchmaking Project Update"
        msg["From"] = sender_email
        msg["To"] = row["email"]

        email_body = f"""
Hey {first_name(person_name)},

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, and compatibility overlap.

I truly appreciate you participating and helping make this project possible.

- Eriyon
"""

        msg.set_content(email_body.strip())

        print(email_body)
        print("=" * 80)
        print(f"Previewed no-match email to {person_name}")

Hey Mara,

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, and compatibility overlap.

I truly appreciate you participating and helping make this project possible.

- Eriyon

================================================================================
Previewed no-match email to Mara Matta

Hey Crystal,

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, and compatibility overlap.

I truly appreciate you participating and helping make this project possible.

- Eriyon

================================================================================
Previewed no-match email to Crystal Stewart

Hey Danny,

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, and compatibility overlap.

I truly appreciate you participating and helping make this project possible.

- Eriyon

================================================================================
Previewed no-match email to Danny Ashcraft

Hey Sola,

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, and compatibility overlap.

I truly appreciate you participating and helping make this project possible.

- Eriyon

================================================================================
Previewed no-match email to Sola Mewha

Hey Sara,

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, and compatibility overlap.

I truly appreciate you participating and helping make this project possible.

- Eriyon

================================================================================
Previewed no-match email to Sara Walkup

Hey Samantha,

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, and compatibility overlap.

I truly appreciate you participating and helping make this project possible.

- Eriyon

================================================================================
Previewed no-match email to Samantha S

Hey Natalie,

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, and compatibility overlap.

I truly appreciate you participating and helping make this project possible.

- Eriyon

================================================================================
Previewed no-match email to Natalie

Hey Maria,

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, and compatibility overlap.

I truly appreciate you participating and helping make this project possible.

- Eriyon

================================================================================
Previewed no-match email to Maria

Hey Eyvaughn,

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, and compatibility overlap.

I truly appreciate you participating and helping make this project possible.

- Eriyon

================================================================================
Previewed no-match email to Eyvaughn Standifer

Hey Sarah,

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, and compatibility overlap.

I truly appreciate you participating and helping make this project possible.

- Eriyon

================================================================================
Previewed no-match email to Sarah Dooley

Hey Lauren,

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, and compatibility overlap.

I truly appreciate you participating and helping make this project possible.

- Eriyon

================================================================================
Previewed no-match email to Lauren

Hey Brian,

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, and compatibility overlap.

I truly appreciate you participating and helping make this project possible.

- Eriyon

================================================================================
Previewed no-match email to Brian

Hey Lindsay,

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, and compatibility overlap.

I truly appreciate you participating and helping make this project possible.

- Eriyon

================================================================================
Previewed no-match email to Lindsay Rogers

Hey Niki,

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, and compatibility overlap.

I truly appreciate you participating and helping make this project possible.

- Eriyon

================================================================================
Previewed no-match email to Niki

Hey Michelle,

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, and compatibility overlap.

I truly appreciate you participating and helping make this project possible.

- Eriyon

================================================================================
Previewed no-match email to Michelle

Hey Lissa,

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, and compatibility overlap.

I truly appreciate you participating and helping make this project possible.

- Eriyon

================================================================================
Previewed no-match email to Lissa

Hey Julien,

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, and compatibility overlap.

I truly appreciate you participating and helping make this project possible.

- Eriyon

================================================================================
Previewed no-match email to Julien Medel

Hey Katy,

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, and compatibility overlap.

I truly appreciate you participating and helping make this project possible.

- Eriyon

================================================================================
Previewed no-match email to Katy

Hey Isha,

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, and compatibility overlap.

I truly appreciate you participating and helping make this project possible.

- Eriyon

================================================================================
Previewed no-match email to Isha Oberoi

Hey Edona,

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, and compatibility overlap.

I truly appreciate you participating and helping make this project possible.

- Eriyon

================================================================================
Previewed no-match email to Edona

Hey Nikohl,

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, and compatibility overlap.

I truly appreciate you participating and helping make this project possible.

- Eriyon

================================================================================
Previewed no-match email to Nikohl

Hey Dave,

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, and compatibility overlap.

I truly appreciate you participating and helping make this project possible.

- Eriyon

================================================================================
Previewed no-match email to Dave

Hey Andrew,

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, and compatibility overlap.

I truly appreciate you participating and helping make this project possible.

- Eriyon

================================================================================
Previewed no-match email to Andrew Fabry

Hey Alissa,

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, and compatibility overlap.

I truly appreciate you participating and helping make this project possible.

- Eriyon

================================================================================
Previewed no-match email to Alissa

Hey Puneet,

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, and compatibility overlap.

I truly appreciate you participating and helping make this project possible.

- Eriyon

================================================================================
Previewed no-match email to Puneet

Hey Terri,

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, and compatibility overlap.

I truly appreciate you participating and helping make this project possible.

- Eriyon

================================================================================
Previewed no-match email to Terri

Hey Samantha,

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, and compatibility overlap.

I truly appreciate you participating and helping make this project possible.

- Eriyon

================================================================================
Previewed no-match email to Samantha Jacobs

Hey Kate,

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, and compatibility overlap.

I truly appreciate you participating and helping make this project possible.

- Eriyon

================================================================================
Previewed no-match email to Kate

In [ ]:
#Save files
match_emails_df.to_csv(r"\\ad.wayne.edu\Users\ex4360\Documents\Blind Date Detroit\Match Rounds\match_emails_backup_before_sending.csv ", index=False)
no_match_df.to_csv(r"\\ad.wayne.edu\Users\ex4360\Documents\Blind Date Detroit\Match Rounds\no_match_backup_before_sending.csv", index=False)

In [ ]:
# TEST NO-MATCH EMAIL TO YOURSELF

with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:

    smtp.login(sender_email, app_password)

    def first_name(full_name):
        return str(full_name).split()[0]

    # clean names
    df["name"] = df["name"].astype(str).str.strip()

    # grab first no-match row
    row = no_match_df.iloc[0]

    person_name = row["name"]

    msg = EmailMessage()

    msg["Subject"] = "TEST - Blind Matchmaking Project Update"
    msg["From"] = sender_email

    # SEND TO YOURSELF
    msg["To"] = "blindmatchdetroit@gmail.com"

    email_body = f"""
Hey {first_name(person_name)},

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, and compatibility overlap.

I truly appreciate you participating and helping make this project possible.

If feedback is positive overall, there will likely be another round in the future.

- Eriyon
"""

    msg.set_content(email_body.strip())

    smtp.send_message(msg)

    print("Test no-match email sent successfully.")

NameError: name 'smtplib' is not defined

In [ ]:
# REAL MATCH EMAIL SEND

sent_pairs = set()

with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:

    smtp.login(sender_email, app_password)

    def first_name(full_name):
        return str(full_name).split()[0]

    # clean names
    df["name"] = df["name"].astype(str).str.strip()
    match_emails_df["Person"] = match_emails_df["Person"].astype(str).str.strip()
    match_emails_df["Match"] = match_emails_df["Match"].astype(str).str.strip()

    for index, row in match_emails_df.iterrows():

        person_name = row["Person"]
        match_name = row["Match"]
        score = row["Score"]

        person_first = first_name(person_name)
        match_first = first_name(match_name)

        if pd.isna(match_name) or score == 0:
            continue

        pair = tuple(sorted([person_name, match_name]))

        if pair in sent_pairs:
            continue

        sent_pairs.add(pair)

        person_rows = df[df["name"] == person_name]
        match_rows = df[df["name"] == match_name]

        if person_rows.empty:
            print("Missing person:", person_name)
            continue

        if match_rows.empty:
            print("Missing match:", match_name)
            continue

        person = person_rows.iloc[0]
        match = match_rows.iloc[0]

        # shared availability
        shared_days = set(
            str(person["best_days_available"]).split(",")
        ).intersection(
            set(str(match["best_days_available"]).split(","))
        )

        shared_times = set(
            str(person["best_time_availabilty"]).split(",")
        ).intersection(
            set(str(match["best_time_availabilty"]).split(","))
        )

        shared_days_text = ", ".join(shared_days)
        shared_times_text = ", ".join(shared_times)

        shared_days_output = (
            f"Shared Days: {shared_days_text}"
            if shared_days_text
            else "Shared Days: No overlapping days listed"
        )

        shared_times_output = (
            f"Shared Times: {shared_times_text}"
            if shared_times_text
            else "Shared Times: No overlapping times listed"
        )

        # email
        msg = EmailMessage()

        msg["Subject"] = "Your Blind Match"
        msg["From"] = sender_email

        # REAL SEND
        msg["To"] = person["email"]
        msg["Cc"] = match["email"]

        email_body = f"""
Hey {person_first} and {match_first},

You two matched!

Shared Availability:
{shared_days_output}
{shared_times_output}

About {person_first}:

Ideal First Date:
{person["ideal_first_date"]}

Age: {person["age"]}
Area: {person["city/area"]}

Bio:
{person["short_bio/about_you"]}

About {match_first}:

Ideal First Date:
{match["ideal_first_date"]}

Age: {match["age"]}
Area: {match["city/area"]}

Bio:
{match["short_bio/about_you"]}

Feel free to reply to this email and connect.

Please keep things respectful, open-minded, and low pressure throughout the experience. Also remember to meet in public places and prioritize safety.

Thanks again for participating and helping make this project possible.

- Eriyon
"""

        msg.set_content(email_body.strip())

        smtp.send_message(msg)

        print(f"Sent match email to {person_first} and {match_first}")

Sent match email to Corey and Pritika
Sent match email to Taylor and Jeromy
Sent match email to Suhas and Regan
Sent match email to Will and KayDee
Sent match email to zachary and Mady
Sent match email to Matt and Madison
Sent match email to Keegan and Olivia
Sent match email to Kiara and Julien
Sent match email to Bryan and Rhiannon
Sent match email to Samantha and Carlos
Sent match email to Dishawn and Rhiannon
Sent match email to Melanie and Vincenzo
Sent match email to Eduardo and Leila
Sent match email to Jonah and KayDee
Sent match email to Vanessa and Nihal
Sent match email to Fahad and Marah
Sent match email to Ana and Prashanth
Sent match email to Spencer and Mark
Sent match email to Vincenzo and Olivia
Sent match email to Hugo and Regan
Sent match email to James and Emily
Sent match email to Aaron and Arshya
Sent match email to Maya and Alex
Sent match email to John and Dani
Sent match email to Mazen and Kim
Sent match email to Jeremy and reigan
Sent match email to Travis and Amanda
Sent match email to Lily and Eric
Sent match email to Alec and Emily
Sent match email to Prabhjit and Arshya
Sent match email to Amanda and Jeromy
Sent match email to Adam and Lily
Sent match email to Justis and Carlos
Sent match email to Eriyon and Angela
Sent match email to Sai and Mady
Sent match email to Mark and Danny
Sent match email to Julian and Pritika
Sent match email to Tony and Lily
Sent match email to Pritika and Tyler
Sent match email to Shreyas and reigan
Sent match email to Tommy and Angela
Sent match email to David and Sabina
Sent match email to Emily and Puneet
Sent match email to reigan and Aldo
Sent match email to Mitchell and Sabina
Sent match email to Madison and Andrew
Sent match email to Brittiney and Sean
Sent match email to Jeff and Diamond
Sent match email to Justin and Jenna
Sent match email to Jenna and Sean
Sent match email to Spencer and Dani
Sent match email to Evan and Marah
Sent match email to Carlos and Vivien
Sent match email to Marah and Nihal
Sent match email to Angela and Aldo
Sent match email to Jennifer and Prashanth
Sent match email to Nishant and Leila
Sent match email to Evan and Vivien
Sent match email to Prashanth and Kim
Sent match email to Lisa and Tyler
Sent match email to Kwame and Madi
Sent match email to Matthew and Madi
Sent match email to Halle and Jonathan
Sent match email to Regan and Dave
Sent match email to Dani and Dave
Sent match email to Aldo and MELANIE
Sent match email to Olivia and Sai
Sent match email to Sai and Lucia
Sent match email to KayDee and Andrew
Sent match email to Emi and Leonel
Sent match email to Sean and Lucia
Sent match email to Halie and Alex
Sent match email to Madi and Leonel
Sent match email to Rob and MELANIE
Sent match email to Diamond and Quinton
Sent match email to Arshya and Nick
Sent match email to Vivien and Harjas
Sent match email to Kim and Quinton
Sent match email to Lily and Ethan
Sent match email to Sabina and Nick
Sent match email to Mady and Andrew
Sent match email to Eriyon and Regan
Sent match email to Eriyon and Kiara
Sent match email to Eriyon and KayDee
Sent match email to Alejandro and KayDee
Sent match email to Ethan and KayDee
Sent match email to Abhi and Angela
Sent match email to Nihal and Angela
Sent match email to Tyler and KayDee
Sent match email to Eric and Kiara
Sent match email to Ryjean and Lily
Sent match email to Jonathan and Regan
Sent match email to Harjas and Angela
Sent match email to Jeromy and KayDee
Sent match email to Leila and Sai

SMTPDataError: (421, b'4.3.0 Temporary System Problem. Try again later. For more information, go to\n4.3.0  https://support.google.com/a/answer/3221692 6a1803df08f44-8cc80dcec8esm47542196d6.7 - gsmtp')

In [ ]:
# REAL NO-MATCH EMAIL SEND

with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:

    smtp.login(sender_email, app_password)

    def first_name(full_name):
        return str(full_name).split()[0]

    df["name"] = df["name"].astype(str).str.strip()

    for index, row in no_match_df.iterrows():

        person_name = row["name"]

        msg = EmailMessage()

        msg["Subject"] = "Blind Matchmaking Project Update"
        msg["From"] = sender_email

        # REAL SEND
        msg["To"] = row["email"]

        email_body = f"""
Hey {first_name(person_name)},

Thank you again for participating in the Blind Matchmaking Project.

Unfortunately, I wasn’t able to find a compatible match for you this round. Please don’t feel discouraged — sometimes it simply comes down to participant ratios, preferences, compatibility overlap, and overall location logistics.

I truly appreciate you participating and helping make this project possible.

If feedback is positive overall, there will likely be another round in the future.

- Eriyon
"""

        msg.set_content(email_body.strip())

        smtp.send_message(msg)

        print(f"Sent no-match email to {person_name}")

In [ ]:
import imaplib
import email
from email.header import decode_header

imap = imaplib.IMAP4_SSL("imap.gmail.com")
imap.login(sender_email, app_password)

imap.select('"[Gmail]/Sent Mail"')

status, messages = imap.search(
    None,
    '(SUBJECT "Your Blind Match")'
)

sent_ids = messages[0].split()

sent_recipients = set()

for msg_id in sent_ids:
    status, msg_data = imap.fetch(msg_id, "(RFC822)")
    msg = email.message_from_bytes(msg_data[0][1])

    to_field = msg.get("To", "")
    cc_field = msg.get("Cc", "")

    all_recipients = to_field + "," + cc_field

    for e in all_recipients.split(","):
        clean_email = e.strip().lower()
        if clean_email:
            sent_recipients.add(clean_email)

imap.logout()

sent_recipients

{'01justislynn@gmail.com',
 '900602019.reid@gmail.com',
 'aaron.bowes@outlook.com',
 'abhijeet.antin@gmail.com',
 'adamsells1987@gmail.com',
 'afabry@comcast.net',
 'afranikwame@hotmail.com',
 'aldo.j.cavazos.l@gmail.com',
 'alecbas@yahoo.com',
 'alexander.rea5@yahoo.com',
 'aloaperkins@gmail.com',
 'amandamarie795@gmail.com',
 'anacedilloemail@gmail.com',
 'angierodriguez017@gmail.com',
 'arshya.g@gmail.com',
 'asdmedel@gmail.com',
 'bernsmadalyn@gmail.com',
 'betelmel@umich.edu',
 'bsempasa86@gmail.com',
 'coreyross1996@gmail.com',
 'danielle132665@gmail.com',
 'danny ashcraft <dashcraftjr@gmail.com>',
 'dashcraftjr@gmail.com',
 'davidcholak18@gmail.com',
 'diamond.hawkins29@yahoo.com',
 'dishawnthiran@yahoo.com',
 'edcerame@gmail.com',
 'elliott302@gmail.com',
 'emilyhowse59@gmail.com',
 'emssalalouf@gmail.com',
 'ericgs@umich.edu',
 'eriyonadams10@gmail.com',
 'ethantd123@gmail.com',
 'evanfd06@gmail.com',
 'fetti1bp@gmail.com',
 'fpfahad@gmail.com',
 'francis.vincenzo@gmail.com',
 'greer.kiara@yahoo.com',
 'hajona17@gmail.com',
 'halchambers8@gmail.com',
 'hugo1_bolanos@hotmail.com',
 'ijongminee@gmail.com',
 'invertedvariable@gmail.com',
 'jbeltowski26@gmail.com',
 'jdpaulino2016@gmail.com',
 'jerooomyidk@gmail.com',
 'jonah0730@att.net',
 'jrperugi@gmail.com',
 'jryurgil@gmail.com',
 'jtogger@gmail.com',
 'julianfascio@outlook.com',
 'justin.sean95@gmail.com',
 'kd.muhleck@gmail.com',
 'keeganmccorry@gmail.com',
 'kiimschreiber@gmail.com',
 'leila.anani@gmail.com',
 'leonel.cuba213@gmail.com',
 'lillianrobinson004@gmail.com',
 'lilynguyenn1994@gmail.com',
 'limonkay@gmail.com',
 'lisa.sun333@gmail.com',
 'luciamagalysosa@gmail.com',
 'madalynbaczkowski@gmail.com',
 'madisonharbort@yahoo.com',
 'marahsgamez@gmail.com',
 'markanderson159@gmail.com',
 'matt.grunz1@gmail.com',
 'matthewhorne342@gmail.com',
 'mazen.rmca@gmail.com',
 'me@evanbradley.org',
 'melwalters4848@gmail.com',
 'mitchelltower19@yahoo.com',
 'nicholas.a.hughes17@gmail.com',
 'nihalnavale@outlook.com',
 'nishantsood5@gmail.com',
 'nohemigarcia383@gmail.com',
 'opatercsak@gmail.com',
 'owenspencer1995@gmail.com',
 'prabhjitsmutneja@outlook.com',
 'prashanth.sai679@gmail.com',
 'quangwenhao@gmail.com',
 'quinton.lemanski@gmail.com',
 'reganhavens@gmail.com',
 'reiganhendo@yahoo.com',
 'rhiannonelaine17@gmail.com',
 'rreeve6@gmail.com',
 'sabinamustic@gmail.com',
 'samanthamj26@gmail.com',
 'shreyasbharadwajbg@gmail.com',
 'singh.harjas8@gmail.com',
 'slangd90@gmail.com',
 'smyint@msgcu.org',
 'spedmonds47@gmail.com',
 'spencer.e.malley@gmail.com',
 'suhas1597@gmail.com',
 'taylorcarlini@gmail.com',
 'tbrown12@svsu.edu',
 'testsubject273@gmail.com',
 'tomlinsonhes@gmail.com',
 'tommygun4563@yahoo.com',
 'travismconte@gmail.com',
 'tumblertony043@gmail.com',
 'vanessa.johnson1216@gmail.com',
 'vivienjames15@gmail.com',
 'williamrittenhouse8@gmail.com',
 'zageagle@gmail.com'}

In [ ]:
match_emails_df["Person Email"] = match_emails_df["Person Email"].str.lower().str.strip()
match_emails_df["Match Email"] = match_emails_df["Match Email"].str.lower().str.strip()

In [ ]:
# CLEAN EMAILS FIRST

match_emails_df["Person Email"] = (
    match_emails_df["Person Email"]
    .astype(str)
    .str.lower()
    .str.strip()
)

match_emails_df["Match Email"] = (
    match_emails_df["Match Email"]
    .astype(str)
    .str.lower()
    .str.strip()
)

# SHOULD RECEIVE EMAILS
# combines both Person Email + Match Email

should_receive_emails = set(
    match_emails_df["Person Email"]
).union(
    set(match_emails_df["Match Email"])
)

# CLEAN SENT EMAILS FROM GMAIL

sent_emails_clean = set(
    email.lower().strip()
    for email in sent_recipients
)

# FIND MISSING EMAILS

missing_emails = (
    should_receive_emails - sent_emails_clean
)

print(missing_emails)

# CREATE DATAFRAME OF MISSING PEOPLE

missing_match_emails_df = match_emails_df[
    (
        match_emails_df["Person Email"]
        .isin(missing_emails)
    )
    |
    (
        match_emails_df["Match Email"]
        .isin(missing_emails)
    )
]

# SHOW RESULTS

missing_match_emails_df[
    [
        "Person",
        "Person Email",
        "Match",
        "Match Email"
    ]
]

{'edsilva@umich.edu', 'nan', 'waldman.shayna@gmail.com', 'kyleruss27@gmail.com', 'viguldesai76@gmail.com', 'migoodwin.49@gmail.com', 'sam.sovran@gmail.com', 'acupadhyay@oakland.edu', 'k.e.smith.1986@gmail.com', '8x2dmvyfv9@privaterelay.appleid.com', 'etraskos11@gmail.com'}

,Person,Person Email,Match,Match Email
81,Eriyon Adams,nan,Rhiannon Shook,rhiannonelaine17@gmail.com
82,Eriyon Adams,nan,Kiara Greer,greer.kiara@yahoo.com
83,Eriyon Adams,nan,KayDee,kd.muhleck@gmail.com
95,Kyle Russ,kyleruss27@gmail.com,Rhiannon Shook,rhiannonelaine17@gmail.com
99,Evan D'Silva,edsilva@umich.edu,reigan Henderson,reiganhendo@yahoo.com
100,Michael Goodwin,migoodwin.49@gmail.com,Taylor Carlini,taylorcarlini@gmail.com
106,Ashwin,acupadhyay@oakland.edu,KayDee,kd.muhleck@gmail.com
107,Sam Sovran,sam.sovran@gmail.com,Karen Smith,k.e.smith.1986@gmail.com
108,Karen Smith,k.e.smith.1986@gmail.com,Vincenzo Francis,francis.vincenzo@gmail.com
109,Shayna,waldman.shayna@gmail.com,Vincenzo Francis,francis.vincenzo@gmail.com
110,Vigul Desai,viguldesai76@gmail.com,Vincenzo Francis,francis.vincenzo@gmail.com
111,Loren Shevitz,8x2dmvyfv9@privaterelay.appleid.com,Karen Smith,k.e.smith.1986@gmail.com
112,Ryjean Reid,900602019.reid@gmail.com,Karen Smith,k.e.smith.1986@gmail.com
113,Erica Traskos,etraskos11@gmail.com,Alex,alexander.rea5@yahoo.com